// Round 3: Add curated food entries
const fs = require('fs');

let nextId = 3600;

function makeEntry(name, categories, health = [], allergens = [], searchAliases = []) {
  const id = `item_${String(nextId).padStart(5, '0')}`;
  nextId++;
  const entry = { id, name, categories, attributes: { health, allergens } };
  if (searchAliases.length > 0) entry.attributes.searchAliases = searchAliases;
  return entry;
}

// ===== COMMON + FULL (nationally known, ≥3 provinces, real dishes) =====
const commonAndFull = [
  // --- 川菜 ---
  makeEntry('豆花牛肉',
    ['cuisine_chuan', 'meal_lunch', 'meal_dinner', 'food_beef', 'dish_main', 'allergen_soy', 'allergen_chili'],
    ['spicy'], ['soy']),
  makeEntry('豆花肥肠',
    ['cuisine_chuan', 'meal_lunch', 'meal_dinner', 'food_meat', 'dish_main', 'allergen_soy', 'allergen_chili'],
    ['spicy'], ['soy']),
  makeEntry('藤椒鱼',
    ['cuisine_chuan', 'meal_lunch', 'meal_dinner', 'food_seafood', 'dish_main', 'allergen_fish', 'allergen_chili'],
    ['spicy'], ['fish']),
  makeEntry('麻辣牛肉',
    ['cuisine_chuan', 'meal_lunch', 'meal_dinner', 'food_beef', 'dish_main', 'allergen_chili', 'allergen_sesame'],
    ['spicy'], ['sesame']),
  makeEntry('冒烤鸭',
    ['cuisine_chuan', 'meal_lunch', 'meal_dinner', 'food_poultry', 'dish_main', 'allergen_chili'],
    ['spicy'], []),

  // --- 家常菜 ---
  makeEntry('可乐鸡翅',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_poultry', 'dish_main'],
    [], []),
  makeEntry('可乐排骨',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_pork', 'dish_main'],
    [], []),
  makeEntry('糖醋丸子',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_pork', 'dish_main'],
    ['sour'], []),
  makeEntry('蒜蓉蒸茄子',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_vegetarian', 'dish_main', 'allergen_garlic'],
    [], []),
  makeEntry('鱼香茄子煲',
    ['cuisine_chuan', 'cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_vegetarian', 'dish_main', 'allergen_chili', 'allergen_garlic'],
    ['spicy'], []),
  makeEntry('鱼香肉丝面',
    ['cuisine_chuan', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_staple', 'allergen_gluten', 'allergen_chili'],
    ['spicy'], ['gluten']),
  makeEntry('麻婆豆腐面',
    ['cuisine_chuan', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_staple', 'allergen_gluten', 'allergen_soy', 'allergen_chili'],
    ['spicy'], ['gluten', 'soy']),
  makeEntry('宫保鸡丁面',
    ['cuisine_chuan', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_staple', 'allergen_gluten', 'allergen_chili', 'allergen_peanut'],
    ['spicy'], ['gluten', 'peanut']),
  makeEntry('番茄牛腩',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_beef', 'dish_main', 'health_high_protein'],
    ['sour'], []),
  makeEntry('番茄牛腩面',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_staple', 'allergen_gluten'],
    ['sour'], ['gluten']),
  makeEntry('番茄牛腩饭',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_rice', 'dish_staple'],
    ['sour'], []),
  makeEntry('土豆烧牛肉',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_beef', 'dish_main', 'health_high_protein'],
    [], []),
  makeEntry('土豆烧排骨',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_pork', 'dish_main'],
    [], []),
  makeEntry('土豆烧鸡',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_poultry', 'dish_main'],
    [], []),
  makeEntry('红烧牛肉面',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_staple', 'allergen_gluten', 'allergen_soy'],
    [], ['gluten', 'soy']),
  makeEntry('红烧排骨面',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_staple', 'allergen_gluten'],
    [], ['gluten']),
  makeEntry('红烧鸡块面',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_staple', 'allergen_gluten'],
    [], ['gluten']),
  makeEntry('酸菜肉丝面',
    ['cuisine_dongbei', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_staple', 'allergen_gluten'],
    ['sour'], ['gluten']),
  makeEntry('榨菜肉丝面',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_staple', 'allergen_gluten'],
    [], ['gluten']),
  makeEntry('三鲜面',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_staple', 'allergen_gluten', 'allergen_shellfish'],
    [], ['gluten', 'seafood']),

  // --- 凉菜/前菜 ---
  makeEntry('皮蛋豆腐',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_vegetarian', 'dish_appetizer', 'allergen_soy', 'allergen_egg'],
    ['light'], ['soy', 'egg']),
  makeEntry('小葱拌豆腐',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_vegetarian', 'dish_appetizer', 'allergen_soy', 'allergen_onion'],
    ['light'], ['soy']),
  makeEntry('老醋花生',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'meal_midnight', 'food_vegetarian', 'dish_appetizer', 'allergen_peanut'],
    ['sour'], ['peanut']),
  makeEntry('凉拌海带',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_vegetarian', 'dish_appetizer', 'allergen_garlic'],
    ['light', 'low_calorie'], []),
  makeEntry('凉拌三丝',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_vegetarian', 'dish_appetizer', 'allergen_soy', 'allergen_garlic'],
    ['light'], ['soy']),
  makeEntry('大拌菜',
    ['cuisine_dongbei', 'meal_lunch', 'meal_dinner', 'food_vegetarian', 'dish_salad', 'health_light', 'health_vegan'],
    ['light'], []),

  // --- 汤品 ---
  makeEntry('酸辣汤',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_soup', 'dish_soup', 'allergen_egg', 'allergen_soy', 'allergen_chili'],
    ['sour', 'spicy'], ['egg', 'soy']),
  makeEntry('玉米排骨汤',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_soup', 'dish_soup', 'health_nourishing'],
    ['nourishing'], []),
  makeEntry('海带排骨汤',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_soup', 'dish_soup', 'health_nourishing'],
    ['nourishing'], []),
  makeEntry('冬瓜排骨汤',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_soup', 'dish_soup', 'health_nourishing', 'health_light'],
    ['nourishing', 'light'], []),
  makeEntry('萝卜排骨汤',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_soup', 'dish_soup', 'health_nourishing'],
    ['nourishing'], []),
  makeEntry('鱼头豆腐汤',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_soup', 'dish_soup', 'allergen_fish', 'allergen_soy', 'health_nourishing'],
    ['nourishing'], ['fish', 'soy']),
  makeEntry('鲫鱼豆腐汤',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_soup', 'dish_soup', 'allergen_fish', 'allergen_soy', 'health_nourishing'],
    ['nourishing'], ['fish', 'soy']),
  makeEntry('乌鸡汤',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_soup', 'dish_soup', 'health_nourishing'],
    ['nourishing'], []),
  makeEntry('老母鸡汤',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_soup', 'dish_soup', 'health_nourishing'],
    ['nourishing'], []),
  makeEntry('黄豆猪蹄汤',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_soup', 'dish_soup', 'health_nourishing', 'allergen_soy'],
    ['nourishing'], ['soy']),

  // --- 粤菜 ---
  makeEntry('肠粉',
    ['cuisine_yue', 'meal_breakfast', 'meal_lunch', 'food_rice', 'dish_snack', 'allergen_gluten'],
    [], ['gluten']),
  makeEntry('腊味煲仔饭',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_rice', 'dish_staple', 'allergen_soy'],
    [], ['soy']),
  makeEntry('滑鸡煲仔饭',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_rice', 'food_poultry', 'dish_staple'],
    [], []),
  makeEntry('窝蛋牛肉饭',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_rice', 'food_beef', 'dish_staple', 'allergen_egg'],
    [], ['egg']),
  makeEntry('隆江猪脚',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_pork', 'dish_main', 'health_high_protein'],
    [], []),
  makeEntry('金沙虾',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_seafood', 'dish_main', 'allergen_shellfish', 'allergen_egg'],
    [], ['seafood', 'egg']),
  makeEntry('椒盐豆腐',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_vegetarian', 'dish_main', 'allergen_soy'],
    [], ['soy']),
  makeEntry('避风塘炒蟹',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_seafood', 'dish_main', 'allergen_shellfish', 'allergen_garlic'],
    [], ['seafood']),
  makeEntry('避风塘炒虾',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_seafood', 'dish_main', 'allergen_shellfish', 'allergen_garlic'],
    [], ['seafood']),
  makeEntry('啫啫鸡煲',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_poultry', 'food_stew', 'dish_main'],
    [], []),
  makeEntry('啫啫生菜',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_vegetarian', 'dish_main'],
    [], []),
  makeEntry('客家酿豆腐',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_vegetarian', 'dish_main', 'allergen_soy'],
    [], ['soy']),
  makeEntry('潮汕牛肉火锅',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_beef', 'food_hotpot', 'dish_main', 'health_high_protein'],
    [], []),
  makeEntry('潮汕牛肉丸',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_beef', 'dish_snack', 'health_high_protein'],
    [], []),

  // --- 湘菜 ---
  makeEntry('辣炒花蛤',
    ['cuisine_xiang', 'cuisine_chuan', 'meal_lunch', 'meal_dinner', 'meal_midnight', 'food_seafood', 'dish_main', 'allergen_shellfish', 'allergen_chili'],
    ['spicy'], ['seafood']),

  // --- 鲁菜 ---
  makeEntry('葱油鱼',
    ['cuisine_lu', 'meal_lunch', 'meal_dinner', 'food_seafood', 'dish_main', 'allergen_fish', 'allergen_onion'],
    ['light'], ['fish']),
  makeEntry('葱油鸡',
    ['cuisine_lu', 'cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_poultry', 'dish_main', 'allergen_onion'],
    [], []),

  // --- 日式 ---
  makeEntry('日式咖喱',
    ['cuisine_japanese', 'meal_lunch', 'meal_dinner', 'food_meat', 'dish_main', 'allergen_chili', 'allergen_dairy'],
    ['spicy'], ['dairy']),
  makeEntry('印度咖喱',
    ['cuisine_indian', 'meal_lunch', 'meal_dinner', 'food_meat', 'dish_main', 'allergen_chili', 'allergen_dairy'],
    ['spicy'], ['dairy']),
  makeEntry('唐扬鸡块',
    ['cuisine_japanese', 'meal_lunch', 'meal_dinner', 'food_poultry', 'dish_main', 'allergen_gluten', 'allergen_egg'],
    [], ['gluten', 'egg']),
  makeEntry('猪排饭',
    ['cuisine_japanese', 'meal_lunch', 'meal_dinner', 'food_pork', 'food_rice', 'dish_staple', 'allergen_gluten', 'allergen_egg'],
    [], ['gluten', 'egg']),
  makeEntry('鳗鱼饭',
    ['cuisine_japanese', 'meal_lunch', 'meal_dinner', 'food_seafood', 'food_rice', 'dish_staple', 'allergen_fish', 'allergen_soy'],
    [], ['fish', 'soy']),
  makeEntry('牛丼',
    ['cuisine_japanese', 'meal_lunch', 'meal_dinner', 'food_beef', 'food_rice', 'dish_staple', 'allergen_soy', 'allergen_onion'],
    [], ['soy']),
  makeEntry('亲子丼',
    ['cuisine_japanese', 'meal_lunch', 'meal_dinner', 'food_poultry', 'food_rice', 'dish_staple', 'allergen_egg', 'allergen_soy'],
    [], ['egg', 'soy']),
  makeEntry('味噌拉面',
    ['cuisine_japanese', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_staple', 'allergen_gluten', 'allergen_soy'],
    [], ['gluten', 'soy']),

  // --- 韩式 ---
  makeEntry('韩式拌饭',
    ['cuisine_korean', 'meal_lunch', 'meal_dinner', 'food_rice', 'dish_staple', 'allergen_egg', 'allergen_soy', 'allergen_chili'],
    ['spicy'], ['egg', 'soy']),
  makeEntry('韩式冷面',
    ['cuisine_korean', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_staple', 'allergen_gluten', 'allergen_egg'],
    ['sour'], ['gluten', 'egg']),
  makeEntry('韩式炸鸡',
    ['cuisine_korean', 'meal_lunch', 'meal_dinner', 'meal_midnight', 'food_poultry', 'dish_main', 'allergen_gluten', 'allergen_chili'],
    ['spicy'], ['gluten']),
  makeEntry('韩式部队锅',
    ['cuisine_korean', 'meal_lunch', 'meal_dinner', 'food_meat', 'food_hotpot', 'dish_main', 'allergen_chili', 'allergen_soy', 'allergen_gluten'],
    ['spicy'], ['soy', 'gluten']),

  // --- 越南 ---
  makeEntry('越南河粉',
    ['cuisine_vietnamese', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_staple', 'allergen_gluten'],
    ['light'], ['gluten']),
  makeEntry('越南春卷',
    ['cuisine_vietnamese', 'meal_lunch', 'meal_dinner', 'food_vegetarian', 'dish_appetizer', 'allergen_gluten', 'allergen_shellfish'],
    ['light'], ['gluten', 'seafood']),
  makeEntry('越南法棍',
    ['cuisine_vietnamese', 'meal_breakfast', 'meal_lunch', 'food_pancake', 'dish_staple', 'allergen_gluten'],
    [], ['gluten']),

  // --- 西式 ---
  makeEntry('意大利肉酱面',
    ['cuisine_italian', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_staple', 'allergen_gluten', 'allergen_dairy'],
    [], ['gluten', 'dairy']),
  makeEntry('意大利千层面',
    ['cuisine_italian', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_main', 'allergen_gluten', 'allergen_dairy', 'allergen_egg'],
    [], ['gluten', 'dairy', 'egg']),
  makeEntry('披萨',
    ['cuisine_italian', 'cuisine_western', 'meal_lunch', 'meal_dinner', 'food_pancake', 'dish_main', 'allergen_gluten', 'allergen_dairy'],
    [], ['gluten', 'dairy']),
  makeEntry('汉堡',
    ['cuisine_american', 'meal_lunch', 'meal_dinner', 'food_meat', 'dish_main', 'allergen_gluten', 'allergen_dairy'],
    [], ['gluten', 'dairy']),
  makeEntry('三明治',
    ['cuisine_western', 'meal_breakfast', 'meal_lunch', 'food_pancake', 'dish_staple', 'allergen_gluten', 'allergen_dairy'],
    [], ['gluten', 'dairy']),
  makeEntry('凯撒沙拉',
    ['cuisine_western', 'meal_lunch', 'meal_dinner', 'food_vegetarian', 'dish_salad', 'allergen_dairy', 'allergen_egg', 'allergen_gluten'],
    ['light', 'low_calorie'], ['dairy', 'egg', 'gluten']),
  makeEntry('热狗',
    ['cuisine_american', 'meal_lunch', 'meal_dinner', 'food_meat', 'dish_snack', 'allergen_gluten'],
    [], ['gluten']),
  makeEntry('法式可颂',
    ['cuisine_french', 'meal_breakfast', 'meal_afternoon_tea', 'food_dessert', 'dish_dessert', 'allergen_gluten', 'allergen_dairy', 'allergen_egg'],
    [], ['gluten', 'dairy', 'egg']),
  makeEntry('德式烤猪肘',
    ['cuisine_german', 'meal_lunch', 'meal_dinner', 'food_pork', 'dish_main', 'health_high_protein'],
    [], []),
  makeEntry('西班牙海鲜饭',
    ['cuisine_spanish', 'meal_lunch', 'meal_dinner', 'food_seafood', 'food_rice', 'dish_staple', 'allergen_shellfish', 'allergen_fish'],
    [], ['seafood', 'fish']),
  makeEntry('希腊沙拉',
    ['cuisine_greek', 'meal_lunch', 'meal_dinner', 'food_vegetarian', 'dish_salad', 'allergen_dairy', 'allergen_olive'],
    ['light', 'low_calorie'], ['dairy']),
  makeEntry('墨西哥卷饼',
    ['cuisine_mexican', 'meal_lunch', 'meal_dinner', 'food_meat', 'dish_main', 'allergen_gluten', 'allergen_chili'],
    ['spicy'], ['gluten']),
  makeEntry('巴西烤肉',
    ['cuisine_brazilian', 'meal_lunch', 'meal_dinner', 'food_beef', 'food_bbq', 'dish_main', 'health_high_protein'],
    [], []),
  makeEntry('印尼炒饭',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_rice', 'dish_staple', 'allergen_egg', 'allergen_chili', 'allergen_soy'],
    ['spicy'], ['egg', 'soy']),
  makeEntry('马来西亚椰浆饭',
    ['cuisine_malaysian', 'meal_lunch', 'meal_dinner', 'food_rice', 'dish_staple', 'allergen_peanut', 'allergen_chili'],
    ['spicy'], ['peanut']),
  makeEntry('马来西亚叻沙',
    ['cuisine_malaysian', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_staple', 'allergen_gluten', 'allergen_shellfish', 'allergen_chili', 'allergen_dairy'],
    ['spicy'], ['gluten', 'seafood', 'dairy']),
  makeEntry('土耳其烤肉',
    ['cuisine_middle_eastern', 'meal_lunch', 'meal_dinner', 'food_beef', 'food_bbq', 'dish_main', 'allergen_gluten'],
    [], ['gluten']),

  // --- 甜品 ---
  makeEntry('意式提拉米苏',
    ['cuisine_italian', 'meal_afternoon_tea', 'food_dessert', 'dish_dessert', 'allergen_dairy', 'allergen_egg', 'allergen_gluten'],
    [], ['dairy', 'egg', 'gluten']),
  makeEntry('法式焦糖布丁',
    ['cuisine_french', 'meal_afternoon_tea', 'food_dessert', 'dish_dessert', 'allergen_dairy', 'allergen_egg'],
    [], ['dairy', 'egg']),
  makeEntry('美式芝士蛋糕',
    ['cuisine_american', 'meal_afternoon_tea', 'food_dessert', 'dish_dessert', 'allergen_dairy', 'allergen_egg', 'allergen_gluten'],
    [], ['dairy', 'egg', 'gluten']),
  makeEntry('美式布朗尼',
    ['cuisine_american', 'meal_afternoon_tea', 'food_dessert', 'dish_dessert', 'allergen_gluten', 'allergen_egg', 'allergen_dairy', 'allergen_tree_nut'],
    [], ['gluten', 'egg', 'dairy', 'tree nut']),
  makeEntry('美式苹果派',
    ['cuisine_american', 'meal_afternoon_tea', 'food_dessert', 'dish_dessert', 'allergen_gluten', 'allergen_dairy', 'allergen_egg'],
    [], ['gluten', 'dairy', 'egg']),

  // --- 小吃 ---
  makeEntry('腊汁肉夹馍',
    ['cuisine_northwest', 'cuisine_shaanxi', 'meal_breakfast', 'meal_lunch', 'meal_dinner', 'food_pork', 'dish_snack', 'allergen_gluten'],
    [], ['gluten']),
  makeEntry('牛肉泡馍',
    ['cuisine_northwest', 'cuisine_shaanxi', 'meal_breakfast', 'meal_lunch', 'meal_dinner', 'food_beef', 'dish_staple', 'allergen_gluten'],
    [], ['gluten']),
  makeEntry('干炒牛河',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_noodles', 'food_beef', 'dish_staple', 'allergen_gluten', 'allergen_soy'],
    [], ['gluten', 'soy']),
];

// ===== FULL ONLY (regional, 1-2 provinces, real dishes) =====
const fullOnly = [
  makeEntry('冒脑花',
    ['cuisine_chuan', 'meal_lunch', 'meal_dinner', 'food_meat', 'dish_snack', 'allergen_chili'],
    ['spicy'], []),
  makeEntry('冒鸭血',
    ['cuisine_chuan', 'meal_lunch', 'meal_dinner', 'food_meat', 'dish_snack', 'allergen_chili'],
    ['spicy'], []),
  makeEntry('江油肥肠',
    ['cuisine_chuan', 'meal_lunch', 'meal_dinner', 'food_meat', 'dish_main', 'allergen_chili'],
    ['spicy'], []),
  makeEntry('乐山钵钵鸡',
    ['cuisine_chuan', 'meal_lunch', 'meal_dinner', 'meal_midnight', 'food_poultry', 'dish_snack', 'allergen_chili', 'allergen_sesame'],
    ['spicy'], ['sesame']),
  makeEntry('甜皮鸭',
    ['cuisine_chuan', 'meal_lunch', 'meal_dinner', 'food_poultry', 'dish_main'],
    [], []),
  makeEntry('灯影牛肉丝',
    ['cuisine_chuan', 'meal_lunch', 'meal_dinner', 'food_beef', 'dish_snack', 'allergen_chili'],
    ['spicy'], []),
  makeEntry('花椒兔',
    ['cuisine_chuan', 'meal_lunch', 'meal_dinner', 'food_meat', 'dish_main', 'allergen_chili'],
    ['spicy'], []),
  makeEntry('青花椒鱼',
    ['cuisine_chuan', 'meal_lunch', 'meal_dinner', 'food_seafood', 'dish_main', 'allergen_fish', 'allergen_chili'],
    ['spicy'], ['fish']),

  makeEntry('猪肠粉',
    ['cuisine_yue', 'meal_breakfast', 'meal_lunch', 'food_rice', 'dish_snack', 'allergen_soy'],
    [], ['soy']),
  makeEntry('混酱肠粉',
    ['cuisine_yue', 'meal_breakfast', 'meal_lunch', 'food_rice', 'dish_snack', 'allergen_soy', 'allergen_peanut', 'allergen_sesame'],
    [], ['soy', 'peanut', 'sesame']),
  makeEntry('虾饺烧卖',
    ['cuisine_yue', 'meal_breakfast', 'meal_lunch', 'food_seafood', 'dish_snack', 'allergen_shellfish', 'allergen_gluten'],
    [], ['seafood', 'gluten']),
  makeEntry('凤爪排骨饭',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_rice', 'dish_staple', 'allergen_soy'],
    [], ['soy']),
  makeEntry('北菇滑鸡饭',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_rice', 'food_poultry', 'dish_staple'],
    [], []),
  makeEntry('潮汕牛筋丸',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_beef', 'dish_snack', 'health_high_protein'],
    [], []),
  makeEntry('澄海卤鹅',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_poultry', 'dish_main', 'allergen_soy'],
    [], ['soy']),
  makeEntry('姜葱龙虾',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_seafood', 'dish_main', 'allergen_shellfish', 'allergen_ginger', 'allergen_onion'],
    [], ['seafood']),
  makeEntry('椒盐鲜鱿',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_seafood', 'dish_main', 'allergen_shellfish', 'allergen_gluten'],
    [], ['seafood', 'gluten']),
  makeEntry('金沙南瓜',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_vegetarian', 'dish_main', 'allergen_egg'],
    [], ['egg']),
  makeEntry('咸蛋黄炒虾',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_seafood', 'dish_main', 'allergen_shellfish', 'allergen_egg'],
    [], ['seafood', 'egg']),
  makeEntry('顺德鱼生',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_seafood', 'dish_appetizer', 'allergen_fish'],
    ['light'], ['fish']),
  makeEntry('大良炒牛奶',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_egg', 'dish_main', 'allergen_dairy', 'allergen_shellfish'],
    [], ['dairy', 'seafood']),
  makeEntry('豉油皇炒面',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_staple', 'allergen_gluten', 'allergen_soy'],
    [], ['gluten', 'soy']),
  makeEntry('豉油皇煎虾',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_seafood', 'dish_main', 'allergen_shellfish', 'allergen_soy'],
    [], ['seafood', 'soy']),
  makeEntry('椒盐九肚鱼',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_seafood', 'dish_main', 'allergen_fish', 'allergen_gluten'],
    [], ['fish', 'gluten']),
  makeEntry('避风塘茄子',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_vegetarian', 'dish_main', 'allergen_garlic'],
    [], []),
  makeEntry('啫啫猪肠粉',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_rice', 'dish_snack', 'allergen_soy'],
    [], ['soy']),
  makeEntry('啫啫鱼头',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_seafood', 'dish_main', 'allergen_fish', 'allergen_garlic'],
    [], ['fish']),

  makeEntry('逍遥镇胡辣汤',
    ['cuisine_henan', 'meal_breakfast', 'meal_lunch', 'food_soup', 'dish_soup', 'allergen_gluten', 'allergen_chili'],
    ['spicy'], ['gluten']),
  makeEntry('洛阳浆面条',
    ['cuisine_henan', 'meal_lunch', 'meal_dinner', 'food_noodles', 'dish_snack', 'allergen_gluten', 'allergen_soy'],
    ['sour'], ['gluten', 'soy']),

  makeEntry('土家酱香饼',
    ['cuisine_hubei', 'meal_breakfast', 'meal_lunch', 'food_pancake', 'dish_snack', 'allergen_gluten', 'allergen_soy', 'allergen_chili'],
    ['spicy'], ['gluten', 'soy']),
  makeEntry('牛肉羹',
    ['cuisine_min', 'meal_lunch', 'meal_dinner', 'food_soup', 'dish_soup', 'allergen_soy', 'allergen_egg'],
    [], ['soy', 'egg']),
  makeEntry('客家娘酒',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_alcohol', 'dish_beverage', 'allergen_gluten'],
    [], ['gluten']),
  makeEntry('黄骨鱼汤',
    ['cuisine_hubei', 'meal_lunch', 'meal_dinner', 'food_soup', 'dish_soup', 'allergen_fish', 'health_nourishing'],
    ['nourishing'], ['fish']),
  makeEntry('全家福汤',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_soup', 'dish_soup', 'allergen_egg', 'allergen_shellfish', 'health_nourishing'],
    ['nourishing'], ['egg', 'seafood']),
  makeEntry('海鲜豆腐汤',
    ['cuisine_yue', 'meal_lunch', 'meal_dinner', 'food_soup', 'dish_soup', 'allergen_shellfish', 'allergen_soy'],
    ['light'], ['seafood', 'soy']),
  makeEntry('草头饼',
    ['cuisine_shanghai', 'meal_breakfast', 'meal_lunch', 'food_pancake', 'dish_snack', 'allergen_gluten'],
    [], ['gluten']),
  makeEntry('酱肉包',
    ['cuisine_other', 'meal_breakfast', 'meal_lunch', 'food_bun', 'dish_staple', 'allergen_gluten', 'allergen_soy'],
    [], ['gluten', 'soy']),
  makeEntry('韭菜鸡蛋包',
    ['cuisine_other', 'meal_breakfast', 'meal_lunch', 'food_bun', 'dish_staple', 'allergen_gluten', 'allergen_egg'],
    [], ['gluten', 'egg']),
  makeEntry('鲜肉烧麦',
    ['cuisine_other', 'meal_breakfast', 'meal_lunch', 'food_dumpling', 'dish_snack', 'allergen_gluten'],
    [], ['gluten']),
  makeEntry('花生猪蹄汤',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_soup', 'dish_soup', 'allergen_peanut', 'health_nourishing'],
    ['nourishing'], ['peanut']),
  makeEntry('日式铁板烧',
    ['cuisine_japanese', 'meal_lunch', 'meal_dinner', 'food_meat', 'food_seafood', 'dish_main', 'allergen_soy'],
    [], ['soy']),
  makeEntry('日式寿喜烧',
    ['cuisine_japanese', 'meal_lunch', 'meal_dinner', 'food_beef', 'food_hotpot', 'dish_main', 'allergen_egg', 'allergen_soy'],
    [], ['egg', 'soy']),
  makeEntry('日式涮涮锅',
    ['cuisine_japanese', 'meal_lunch', 'meal_dinner', 'food_beef', 'food_hotpot', 'dish_main', 'allergen_soy'],
    [], ['soy']),
  makeEntry('越南滴漏咖啡',
    ['cuisine_vietnamese', 'meal_afternoon_tea', 'food_coffee', 'dish_beverage', 'allergen_dairy'],
    [], ['dairy']),
  makeEntry('法式焗蜗牛',
    ['cuisine_french', 'meal_lunch', 'meal_dinner', 'food_seafood', 'dish_main', 'allergen_dairy'],
    [], ['dairy']),
  makeEntry('法式鹅肝',
    ['cuisine_french', 'meal_lunch', 'meal_dinner', 'food_meat', 'dish_main', 'allergen_dairy'],
    [], ['dairy']),
  makeEntry('西班牙火腿',
    ['cuisine_spanish', 'meal_lunch', 'meal_dinner', 'food_pork', 'dish_appetizer'],
    [], []),
  makeEntry('美式烤火鸡',
    ['cuisine_american', 'meal_lunch', 'meal_dinner', 'food_poultry', 'dish_main', 'health_high_protein'],
    [], []),
  makeEntry('美式烤肋排',
    ['cuisine_american', 'meal_lunch', 'meal_dinner', 'food_pork', 'dish_main', 'health_high_protein'],
    [], []),
  makeEntry('美式奶昔',
    ['cuisine_american', 'meal_afternoon_tea', 'food_dessert', 'dish_beverage', 'allergen_dairy'],
    [], ['dairy']),
  makeEntry('美式松饼',
    ['cuisine_american', 'meal_breakfast', 'meal_afternoon_tea', 'food_dessert', 'dish_dessert', 'allergen_gluten', 'allergen_egg', 'allergen_dairy'],
    [], ['gluten', 'egg', 'dairy']),
  makeEntry('美式华夫饼',
    ['cuisine_american', 'meal_breakfast', 'meal_afternoon_tea', 'food_dessert', 'dish_dessert', 'allergen_gluten', 'allergen_egg', 'allergen_dairy'],
    [], ['gluten', 'egg', 'dairy']),
  makeEntry('美式肉桂卷',
    ['cuisine_american', 'meal_breakfast', 'meal_afternoon_tea', 'food_dessert', 'dish_dessert', 'allergen_gluten', 'allergen_dairy', 'allergen_egg'],
    [], ['gluten', 'dairy', 'egg']),
  makeEntry('美式甜甜圈',
    ['cuisine_american', 'meal_breakfast', 'meal_afternoon_tea', 'food_dessert', 'dish_dessert', 'allergen_gluten', 'allergen_egg', 'allergen_dairy'],
    [], ['gluten', 'egg', 'dairy']),
  makeEntry('印尼沙爹',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_meat', 'food_bbq', 'dish_main', 'allergen_peanut', 'allergen_chili'],
    ['spicy'], ['peanut']),
  makeEntry('摩洛哥塔吉锅',
    ['cuisine_african', 'meal_lunch', 'meal_dinner', 'food_meat', 'food_stew', 'dish_main', 'allergen_chili'],
    ['spicy'], []),
  makeEntry('阿根廷烤肉',
    ['cuisine_brazilian', 'meal_lunch', 'meal_dinner', 'food_beef', 'food_bbq', 'dish_main', 'health_high_protein'],
    [], []),
  makeEntry('古巴三明治',
    ['cuisine_other', 'meal_lunch', 'meal_dinner', 'food_pork', 'dish_main', 'allergen_gluten', 'allergen_dairy'],
    [], ['gluten', 'dairy']),
  makeEntry('夏威夷poke',
    ['cuisine_american', 'meal_lunch', 'meal_dinner', 'food_seafood', 'dish_salad', 'allergen_fish', 'allergen_soy', 'allergen_sesame'],
    ['light', 'high_protein'], ['fish', 'soy', 'sesame']),
  makeEntry('德州烧烤',
    ['cuisine_american', 'meal_lunch', 'meal_dinner', 'food_beef', 'food_bbq', 'dish_main', 'health_high_protein'],
    [], []),
  makeEntry('德州牛排',
    ['cuisine_american', 'meal_lunch', 'meal_dinner', 'food_beef', 'dish_main', 'health_high_protein'],
    [], []),
  makeEntry('乌梅汤',
    ['cuisine_other', 'meal_afternoon_tea', 'food_fruit_tea', 'dish_beverage'],
    ['sour'], []),
  makeEntry('桂花酸梅汤',
    ['cuisine_beijing', 'meal_afternoon_tea', 'food_fruit_tea', 'dish_beverage'],
    ['sour'], []),
  makeEntry('红糖发糕',
    ['cuisine_other', 'meal_breakfast', 'meal_afternoon_tea', 'food_dessert', 'dish_dessert', 'allergen_gluten'],
    [], ['gluten']),
  makeEntry('红枣粽子',
    ['cuisine_other', 'meal_breakfast', 'meal_afternoon_tea', 'food_rice', 'dish_dessert', 'allergen_gluten'],
    [], ['gluten']),
  makeEntry('清明果',
    ['cuisine_zhe', 'cuisine_min', 'meal_breakfast', 'meal_afternoon_tea', 'food_rice', 'dish_dessert', 'allergen_gluten'],
    [], ['gluten']),
  makeEntry('红糖年糕',
    ['cuisine_other', 'meal_breakfast', 'meal_afternoon_tea', 'food_rice', 'dish_dessert', 'allergen_gluten'],
    [], ['gluten']),
];

// ===== EXECUTE =====
const commonPath = './js/ingredients_common.json';
const fullPath = './js/ingredients_full.json';

const common = JSON.parse(fs.readFileSync(commonPath, 'utf8'));
const full = JSON.parse(fs.readFileSync(fullPath, 'utf8'));

const existingCommonNames = new Set(common.items.map(x => x.name));
const existingFullNames = new Set(full.items.map(x => x.name));

let commonAdded = 0;
for (const entry of commonAndFull) {
  if (existingCommonNames.has(entry.name)) {
    console.log('SKIP (already in common): ' + entry.name);
    continue;
  }
  common.items.push(entry);
  existingCommonNames.add(entry.name);
  commonAdded++;
  console.log('ADD to common: ' + entry.id + ' - ' + entry.name);
}

let fullAdded = 0;
for (const entry of [...commonAndFull, ...fullOnly]) {
  if (existingFullNames.has(entry.name)) {
    console.log('SKIP (already in full): ' + entry.name);
    continue;
  }
  full.items.push(entry);
  existingFullNames.add(entry.name);
  fullAdded++;
  console.log('ADD to full: ' + entry.id + ' - ' + entry.name);
}

fs.writeFileSync(commonPath, JSON.stringify(common, null, 4), 'utf8');
fs.writeFileSync(fullPath, JSON.stringify(full, null, 4), 'utf8');

console.log('\n=== SUMMARY ===');
console.log('Added to common: ' + commonAdded + ' entries (total: ' + common.items.length + ')');
console.log('Added to full: ' + fullAdded + ' entries (total: ' + full.items.length + ')');