#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
add_more_dishes.py - 追加更多独特菜品，避免与现有重复
"""
import json
import os
import re

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_PATH = os.path.join(BASE_DIR, "js", "ingredients.json")

def load_data():
    with open(SRC_PATH, "r", encoding="utf-8") as f:
        return json.load(f)

def build_name_to_id(categories):
    name_to_id = {}
    for group_name, group in categories.items():
        for name, info in group.items():
            name_to_id[name] = info["id"]
    return name_to_id

def main():
    data = load_data()
    name_to_id = build_name_to_id(data["categories"])
    
    C = lambda name: name_to_id.get(name, "")
    
    # 缩写
    cu = {
        "chuan": C("川菜"), "lu": C("鲁菜"), "yue": C("粤菜"), "su": C("苏菜"),
        "zhe": C("浙菜"), "min": C("闽菜"), "xiang": C("湘菜"), "anhui": C("徽菜(皖)"),
        "yu": C("渝菜"), "beijing": C("京菜"), "shanghai": C("沪菜"), "dongbei": C("东北菜"),
        "northwest": C("西北菜"), "yunnan": C("云南菜"), "guizhou": C("贵州菜"),
        "hubei": C("湖北菜"), "shanxi": C("山西菜"), "gansu": C("甘肃菜"),
        "chongqing": C("重庆菜"), "henan": C("河南菜"), "shaanxi": C("陕西菜"),
        "xinjiang": C("新疆菜"), "guangxi": C("广西菜"), "japanese": C("日式"),
        "korean": C("韩式"), "thai": C("泰式"), "vietnamese": C("越式"),
        "indian": C("印度菜"), "italian": C("意式"), "french": C("法式"),
        "american": C("美式"), "western": C("西餐"), "spanish": C("西班牙菜"),
        "german": C("德式"), "british": C("英式"), "mexican": C("墨西哥菜"),
        "other": C("其他"),
    }
    
    m = {
        "breakfast": C("早餐"), "lunch": C("午餐"), "dinner": C("晚餐"),
        "midnight": C("夜宵"), "afternoon": C("下午茶"),
    }
    
    f = {
        "meat": C("荤菜"), "veg": C("素菜"), "seafood": C("海鲜"), "poultry": C("禽类"),
        "beef": C("牛肉"), "pork": C("猪肉"), "lamb": C("羊肉"), "soup": C("汤羹"),
        "congee": C("粥品"), "stew": C("煲仔"), "rice": C("饭类"), "noodles": C("面食"),
        "dumpling": C("饺子"), "bun": C("包子"), "pancake": C("饼类"), "bbq": C("烧烤"),
        "hotpot": C("火锅"), "stirfry": C("炒菜"), "cold": C("凉菜"), "dessert": C("甜点"),
        "snack": C("小吃"), "wholegrain": C("杂粮"), "fruit_tea": C("果茶"),
        "tea": C("茶水"), "coffee": C("咖啡"), "alcohol": C("酒水"),
    }
    
    d = {
        "staple": C("主食"), "main": C("正餐"), "snack": C("小吃"), "dessert": C("甜点"),
        "beverage": C("饮品"), "soup": C("汤品"), "appetizer": C("前菜"), "salad": C("沙拉"),
    }
    
    h = {
        "low_fat": C("低脂"), "low_cal": C("低卡"), "high_protein": C("高蛋白"),
        "low_sugar": C("低糖"), "sugar_free": C("无糖"), "low_salt": C("低盐"),
        "high_fiber": C("高纤维"), "vegan": C("素食"), "nourishing": C("滋补"),
        "light": C("清淡"),
    }
    
    a = {
        "peanut": C("花生"), "tree_nut": C("坚果"), "dairy": C("乳制品"),
        "egg": C("鸡蛋"), "shellfish": C("海鲜"), "fish": C("鱼类"), "soy": C("大豆"),
        "gluten": C("麸质"), "sesame": C("芝麻"), "celery": C("芹菜"),
        "mustard": C("芥末"), "sulfite": C("亚硫酸盐"), "pork": C("猪肉"),
        "chili": C("辣椒"), "onion": C("葱"), "ginger": C("姜"), "garlic": C("蒜"),
    }
    
    def M(name, cats):
        return {"name": name, "categories": [c for c in cats if c]}
    
    existing_names = {item["name"] for item in data["items"]}
    max_id = 0
    for item in data["items"]:
        m_id = re.search(r"item_(\d+)", item["id"])
        if m_id:
            max_id = max(max_id, int(m_id.group(1)))
    
    print(f"当前: {len(data['items'])} 条记录, max_id={max_id}")
    
    # 新增菜品 - 选择更独特的名称以避免重复
    new_dishes = [
        # === 更多早餐 ===
        M("煎饼果子", [cu["other"], m["breakfast"], m["lunch"], f["pancake"], d["snack"], a["gluten"], a["egg"]]),
        M("甜豆浆", [cu["other"], m["breakfast"], f["tea"], d["beverage"], h["vegan"], a["soy"]]),
        M("咸豆浆", [cu["shanghai"], m["breakfast"], f["tea"], d["beverage"], a["soy"]]),
        M("豆腐脑(甜)", [cu["other"], m["breakfast"], f["veg"], d["snack"], h["vegan"], a["soy"]]),
        M("豆腐脑(咸)", [cu["other"], m["breakfast"], f["veg"], d["snack"], h["vegan"], a["soy"]]),
        M("鲜肉包", [cu["other"], m["breakfast"], m["lunch"], f["bun"], d["snack"], a["gluten"], a["pork"]]),
        M("三鲜包", [cu["other"], m["breakfast"], m["lunch"], f["bun"], d["snack"], a["gluten"], a["pork"], a["egg"]]),
        M("梅干菜包", [cu["zhe"], m["breakfast"], m["lunch"], f["bun"], d["snack"], a["gluten"], a["pork"]]),
        M("流沙包", [cu["yue"], m["breakfast"], m["afternoon"], f["bun"], d["snack"], a["gluten"], a["dairy"], a["egg"]]),
        M("红糖馒头", [cu["other"], m["breakfast"], m["afternoon"], f["bun"], d["snack"], a["gluten"]]),
        M("玉米馒头", [cu["other"], m["breakfast"], m["lunch"], f["bun"], d["staple"], h["high_fiber"], a["gluten"]]),
        M("荞麦馒头", [cu["other"], m["breakfast"], m["lunch"], f["bun"], d["staple"], h["high_fiber"], a["gluten"]]),
        M("窝窝头", [cu["dongbei"], m["breakfast"], m["lunch"], f["wholegrain"], d["staple"], h["high_fiber"]]),
        M("韭菜鸡蛋馅饼", [cu["dongbei"], m["breakfast"], m["lunch"], f["pancake"], d["snack"], a["gluten"], a["egg"]]),
        M("牛肉馅饼", [cu["northwest"], m["breakfast"], m["lunch"], f["pancake"], d["snack"], h["high_protein"], a["gluten"]]),
        M("豆沙馅饼", [cu["other"], m["breakfast"], m["afternoon"], f["pancake"], d["snack"], a["gluten"], a["soy"]]),
        M("豆浆油条套餐", [cu["other"], m["breakfast"], f["tea"], d["beverage"], a["soy"], a["gluten"]]),
        M("蛋饼", [cu["shanghai"], m["breakfast"], f["pancake"], d["snack"], a["gluten"], a["egg"]]),
        M("糍饭糕", [cu["shanghai"], m["breakfast"], f["rice"], d["snack"]]),
        M("蒸饺", [cu["other"], m["breakfast"], m["lunch"], f["dumpling"], d["snack"], a["gluten"]]),
        M("虾饺", [cu["yue"], m["breakfast"], m["lunch"], f["dumpling"], d["snack"], a["gluten"], a["shellfish"]]),
        M("糯米烧麦", [cu["yue"], m["breakfast"], m["lunch"], f["snack"], d["snack"], a["gluten"], a["pork"]]),
        M("鲜肉馄饨", [cu["shanghai"], m["breakfast"], m["lunch"], m["dinner"], f["dumpling"], d["snack"], a["gluten"], a["pork"]]),
        M("荠菜馄饨", [cu["shanghai"], m["breakfast"], m["lunch"], f["dumpling"], d["snack"], h["vegan"], a["gluten"]]),
        M("虾仁馄饨", [cu["shanghai"], m["breakfast"], m["lunch"], f["dumpling"], d["snack"], a["gluten"], a["shellfish"]]),
        M("发糕", [cu["other"], m["breakfast"], m["afternoon"], f["bun"], d["snack"], a["gluten"]]),
        M("米糕", [cu["other"], m["breakfast"], m["afternoon"], f["rice"], d["snack"]]),
        M("红糖糍粑", [cu["chuan"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"]]),
        M("烤包子(新疆)", [cu["xinjiang"], m["breakfast"], m["lunch"], f["bun"], d["snack"], a["gluten"]]),
        M("水煎包", [cu["lu"], m["breakfast"], m["lunch"], f["bun"], d["snack"], a["gluten"], a["pork"]]),
        M("糖饼", [cu["dongbei"], m["breakfast"], m["afternoon"], f["pancake"], d["snack"], a["gluten"]]),
        M("鸡蛋灌饼(加里脊)", [cu["henan"], m["breakfast"], f["pancake"], d["staple"], a["gluten"], a["egg"], a["pork"]]),
        M("掉渣烧饼", [cu["hubei"], m["breakfast"], m["lunch"], f["pancake"], d["snack"], a["gluten"], a["sesame"], a["pork"]]),
        M("酱香饼(土家)", [cu["hubei"], m["breakfast"], m["lunch"], f["pancake"], d["snack"], a["gluten"], a["soy"], a["onion"]]),
        
        # === 更多小吃/零食 ===
        M("麻辣豆干", [cu["chuan"], m["afternoon"], m["midnight"], f["snack"], d["snack"], a["soy"], a["chili"]]),
        M("泡椒凤爪", [cu["chuan"], m["afternoon"], m["midnight"], f["snack"], d["snack"], a["chili"]]),
        M("卤鸭脖", [cu["hubei"], m["afternoon"], m["midnight"], f["poultry"], f["snack"], d["snack"], a["chili"], a["soy"]]),
        M("卤鸭翅", [cu["hubei"], m["afternoon"], m["midnight"], f["poultry"], f["snack"], d["snack"], a["chili"], a["soy"]]),
        M("卤鸭舌", [cu["hubei"], m["afternoon"], m["midnight"], f["poultry"], f["snack"], d["snack"], a["chili"], a["soy"]]),
        M("卤藕片", [cu["hubei"], m["afternoon"], m["midnight"], f["snack"], d["snack"], h["vegan"], a["chili"], a["soy"]]),
        M("卤海带", [cu["hubei"], m["afternoon"], m["midnight"], f["snack"], d["snack"], h["vegan"], a["chili"], a["soy"]]),
        M("卤毛豆", [cu["hubei"], m["afternoon"], m["midnight"], f["snack"], d["snack"], h["vegan"], a["chili"], a["soy"]]),
        M("炸鸡柳", [cu["other"], m["afternoon"], m["midnight"], f["poultry"], f["snack"], d["snack"], a["gluten"]]),
        M("炸鸡架", [cu["other"], m["afternoon"], m["midnight"], f["poultry"], f["snack"], d["snack"]]),
        M("炸藕合", [cu["hubei"], m["afternoon"], m["midnight"], f["snack"], d["snack"], a["gluten"]]),
        M("炸茄盒", [cu["dongbei"], m["afternoon"], m["midnight"], f["snack"], d["snack"], a["gluten"]]),
        M("烤鱿鱼", [cu["other"], m["afternoon"], m["midnight"], f["seafood"], f["bbq"], d["snack"], a["shellfish"], a["chili"]]),
        M("烤生蚝", [cu["yue"], m["afternoon"], m["midnight"], f["seafood"], f["bbq"], d["snack"], h["high_protein"], a["shellfish"], a["garlic"]]),
        M("烤扇贝", [cu["other"], m["afternoon"], m["midnight"], f["seafood"], f["bbq"], d["snack"], h["high_protein"], a["shellfish"], a["garlic"]]),
        M("烤羊排", [cu["xinjiang"], m["lunch"], m["dinner"], m["midnight"], f["lamb"], f["bbq"], d["main"], h["high_protein"], a["chili"]]),
        M("烤猪蹄", [cu["other"], m["afternoon"], m["midnight"], f["pork"], f["bbq"], d["snack"], a["pork"], a["chili"]]),
        M("烤脑花", [cu["chongqing"], m["midnight"], f["pork"], f["bbq"], d["snack"], a["pork"], a["chili"]]),
        M("烤豆皮", [cu["other"], m["afternoon"], m["midnight"], f["bbq"], d["snack"], a["soy"]]),
        M("烤金针菇", [cu["other"], m["afternoon"], m["midnight"], f["bbq"], f["veg"], d["snack"], h["vegan"]]),
        M("烤青椒", [cu["other"], m["afternoon"], m["midnight"], f["bbq"], f["veg"], d["snack"], h["vegan"], a["chili"]]),
        M("烤豆腐", [cu["other"], m["afternoon"], m["midnight"], f["bbq"], f["veg"], d["snack"], h["vegan"], a["soy"]]),
        M("烤年糕", [cu["other"], m["afternoon"], m["midnight"], f["bbq"], d["snack"], a["gluten"]]),
        M("雪花酪", [cu["other"], m["afternoon"], f["dessert"], d["dessert"], a["dairy"]]),
        M("炒酸奶", [cu["other"], m["afternoon"], f["dessert"], d["dessert"], a["dairy"]]),
        M("奶昔", [cu["american"], m["afternoon"], f["dessert"], d["beverage"], a["dairy"]]),
        M("沙冰", [cu["other"], m["afternoon"], f["dessert"], d["beverage"]]),
        M("果冻", [cu["other"], m["afternoon"], f["dessert"], d["dessert"]]),
        M("蛋挞", [cu["yue"], m["afternoon"], m["breakfast"], f["dessert"], d["dessert"], a["gluten"], a["egg"], a["dairy"]]),
        M("葡式蛋挞", [cu["yue"], m["afternoon"], m["breakfast"], f["dessert"], d["dessert"], a["gluten"], a["egg"], a["dairy"]]),
        M("酥皮点心", [cu["other"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"], a["dairy"]]),
        M("凤梨酥", [cu["min"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"], a["dairy"], a["egg"]]),
        M("牛轧糖", [cu["other"], m["afternoon"], f["dessert"], d["dessert"], a["dairy"], a["peanut"]]),
        M("雪花酥", [cu["other"], m["afternoon"], f["dessert"], d["dessert"], a["dairy"], a["gluten"]]),
        M("茯苓饼", [cu["beijing"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"]]),
        M("驴打滚", [cu["beijing"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"], a["soy"]]),
        M("豌豆黄", [cu["beijing"], m["afternoon"], f["dessert"], d["dessert"], h["vegan"], a["soy"]]),
        M("艾窝窝", [cu["beijing"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"]]),
        M("芸豆卷", [cu["beijing"], m["afternoon"], f["dessert"], d["dessert"], h["vegan"], a["soy"]]),
        M("冰糖葫芦", [cu["beijing"], m["afternoon"], f["dessert"], d["dessert"]]),
        M("炒酸奶块", [cu["other"], m["afternoon"], f["dessert"], d["dessert"], a["dairy"]]),
        M("土豆泥", [cu["western"], m["lunch"], m["dinner"], f["veg"], d["appetizer"], h["vegan"]]),
        M("玉米浓汤", [cu["western"], m["lunch"], m["dinner"], f["soup"], d["soup"], a["dairy"]]),
        M("奶油蘑菇汤", [cu["western"], m["lunch"], m["dinner"], f["soup"], d["soup"], a["dairy"]]),
        M("法棍面包", [cu["french"], m["breakfast"], m["lunch"], f["snack"], d["staple"], a["gluten"]]),
        M("可颂", [cu["french"], m["breakfast"], m["afternoon"], f["dessert"], d["snack"], a["gluten"], a["dairy"], a["egg"]]),
        M("马卡龙", [cu["french"], m["afternoon"], f["dessert"], d["dessert"], a["egg"], a["tree_nut"]]),
        M("西班牙海鲜饭", [cu["spanish"], m["lunch"], m["dinner"], f["seafood"], f["rice"], d["staple"], a["shellfish"], a["fish"]]),
        M("德国猪肘", [cu["german"], m["lunch"], m["dinner"], f["pork"], d["main"], a["pork"]]),
        M("英式炸鱼薯条", [cu["british"], m["lunch"], m["dinner"], f["seafood"], d["main"], a["fish"], a["gluten"]]),
        M("墨西哥卷饼", [cu["mexican"], m["lunch"], m["dinner"], f["meat"], d["staple"], a["gluten"], a["chili"]]),
        M("泰式绿咖喱", [cu["thai"], m["lunch"], m["dinner"], f["poultry"], d["main"], a["chili"], a["dairy"]]),
        M("越式春卷", [cu["vietnamese"], m["lunch"], m["dinner"], f["veg"], d["snack"], a["gluten"], a["shellfish"]]),
        M("印度咖喱鸡", [cu["indian"], m["lunch"], m["dinner"], f["poultry"], d["main"], a["chili"], a["dairy"]]),
        M("印度咖喱羊肉", [cu["indian"], m["lunch"], m["dinner"], f["lamb"], d["main"], a["chili"]]),
        M("日式照烧鸡", [cu["japanese"], m["lunch"], m["dinner"], f["poultry"], d["main"], h["high_protein"], a["soy"]]),
        M("日式炸猪排", [cu["japanese"], m["lunch"], m["dinner"], f["pork"], d["main"], a["pork"], a["gluten"]]),
        M("味噌汤", [cu["japanese"], m["lunch"], m["dinner"], f["soup"], d["soup"], a["soy"], a["fish"]]),
        M("乌冬面", [cu["japanese"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"], a["soy"]]),
        M("荞麦面", [cu["japanese"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"]]),
        M("鳗鱼饭", [cu["japanese"], m["lunch"], m["dinner"], f["seafood"], f["rice"], d["staple"], h["high_protein"], a["fish"], a["soy"]]),
        M("日式煎饺", [cu["japanese"], m["lunch"], m["dinner"], f["dumpling"], d["snack"], a["gluten"], a["pork"]]),
        M("韩式泡菜汤", [cu["korean"], m["lunch"], m["dinner"], f["soup"], d["soup"], a["chili"], a["garlic"], a["soy"]]),
        M("韩式炒年糕", [cu["korean"], m["lunch"], m["dinner"], f["snack"], d["snack"], a["chili"], a["gluten"]]),
        M("韩式海鲜饼", [cu["korean"], m["lunch"], m["dinner"], f["seafood"], f["pancake"], d["snack"], a["gluten"], a["shellfish"], a["egg"]]),
        M("韩式拌饭", [cu["korean"], m["lunch"], m["dinner"], f["rice"], d["staple"], a["egg"], a["chili"], a["soy"]]),
        M("大酱汤", [cu["korean"], m["lunch"], m["dinner"], f["soup"], d["soup"], a["soy"], a["chili"], a["garlic"]]),
        M("韩式炸酱面", [cu["korean"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"], a["soy"], a["pork"]]),
        M("韩式米肠", [cu["korean"], m["lunch"], m["dinner"], f["snack"], d["snack"], a["pork"]]),
        
        # === 更多正餐 ===
        M("红烧牛腩", [cu["other"], m["lunch"], m["dinner"], f["beef"], f["stirfry"], d["main"], h["high_protein"], a["soy"]]),
        M("番茄牛腩", [cu["other"], m["lunch"], m["dinner"], f["beef"], f["stew"], d["main"], h["high_protein"]]),
        M("土豆烧牛肉", [cu["dongbei"], m["lunch"], m["dinner"], f["beef"], f["stirfry"], d["main"], h["high_protein"]]),
        M("红烧牛尾", [cu["other"], m["lunch"], m["dinner"], f["beef"], d["main"], h["high_protein"]]),
        M("蚝油牛肉", [cu["yue"], m["lunch"], m["dinner"], f["beef"], f["stirfry"], d["main"], h["high_protein"], a["soy"]]),
        M("沙茶牛肉", [cu["min"], m["lunch"], m["dinner"], f["beef"], f["stirfry"], d["main"], h["high_protein"], a["shellfish"]]),
        M("铁板牛肉", [cu["yue"], m["lunch"], m["dinner"], f["beef"], f["stirfry"], d["main"], h["high_protein"], a["onion"]]),
        M("黑椒牛柳", [cu["yue"], m["lunch"], m["dinner"], f["beef"], f["stirfry"], d["main"], h["high_protein"]]),
        M("野山椒牛肉", [cu["xiang"], m["lunch"], m["dinner"], f["beef"], f["stirfry"], d["main"], h["high_protein"], a["chili"]]),
        M("香菜牛肉", [cu["xiang"], m["lunch"], m["dinner"], f["beef"], f["stirfry"], d["main"], h["high_protein"], a["chili"]]),
        M("孜然牛肉", [cu["xinjiang"], m["lunch"], m["dinner"], f["beef"], f["stirfry"], d["main"], h["high_protein"], a["chili"]]),
        M("尖椒牛肉", [cu["chuan"], m["lunch"], m["dinner"], f["beef"], f["stirfry"], d["main"], h["high_protein"], a["chili"]]),
        M("鱼香牛肉丝", [cu["chuan"], m["lunch"], m["dinner"], f["beef"], f["stirfry"], d["main"], h["high_protein"], a["chili"]]),
        M("红烧带鱼", [cu["other"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["fish"], a["soy"]]),
        M("干炸带鱼", [cu["other"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["fish"]]),
        M("香煎带鱼", [cu["other"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["fish"]]),
        M("红烧鲫鱼", [cu["other"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["fish"], a["soy"]]),
        M("清蒸武昌鱼", [cu["hubei"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], h["low_fat"], h["light"], a["fish"]]),
        M("葱油鱼", [cu["zhe"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["fish"], a["onion"]]),
        M("糖醋鱼", [cu["lu"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["fish"]]),
        M("酱焖鱼", [cu["lu"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["fish"], a["soy"]]),
        M("番茄鱼片", [cu["other"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["fish"]]),
        M("酸汤鱼片", [cu["guizhou"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["fish"], a["chili"]]),
        M("糟溜鱼片", [cu["lu"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["fish"]]),
        M("宫保鱼丁", [cu["chuan"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["fish"], a["peanut"], a["chili"]]),
        M("泡椒牛蛙", [cu["chuan"], m["lunch"], m["dinner"], m["midnight"], f["meat"], f["stirfry"], d["main"], h["high_protein"], a["chili"]]),
        M("干锅牛蛙", [cu["xiang"], m["lunch"], m["dinner"], m["midnight"], f["meat"], f["stirfry"], d["main"], h["high_protein"], a["chili"]]),
        M("香辣蟹", [cu["chuan"], m["lunch"], m["dinner"], f["seafood"], f["stirfry"], d["main"], h["high_protein"], a["shellfish"], a["chili"]]),
        M("姜葱炒蟹", [cu["yue"], m["lunch"], m["dinner"], f["seafood"], f["stirfry"], d["main"], h["high_protein"], a["shellfish"], a["onion"], a["ginger"]]),
        M("蒜蓉粉丝虾", [cu["yue"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["shellfish"], a["garlic"], a["gluten"]]),
        M("铁板虾", [cu["yue"], m["lunch"], m["dinner"], f["seafood"], f["stirfry"], d["main"], h["high_protein"], a["shellfish"]]),
        M("油焖大虾", [cu["lu"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["shellfish"]]),
        M("椒盐皮皮虾", [cu["yue"], m["lunch"], m["dinner"], m["midnight"], f["seafood"], d["main"], h["high_protein"], a["shellfish"]]),
        M("蒜蓉生蚝", [cu["yue"], m["lunch"], m["dinner"], m["midnight"], f["seafood"], d["main"], h["high_protein"], a["shellfish"], a["garlic"]]),
        M("蒜蓉扇贝", [cu["yue"], m["lunch"], m["dinner"], m["midnight"], f["seafood"], d["main"], h["high_protein"], a["shellfish"], a["garlic"]]),
        M("花蛤蒸蛋", [cu["yue"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["shellfish"], a["egg"]]),
        M("辣炒花蛤", [cu["chuan"], m["lunch"], m["dinner"], m["midnight"], f["seafood"], f["stirfry"], d["main"], h["high_protein"], a["shellfish"], a["chili"]]),
        M("辣炒蛏子", [cu["chuan"], m["lunch"], m["dinner"], m["midnight"], f["seafood"], f["stirfry"], d["main"], h["high_protein"], a["shellfish"], a["chili"]]),
        M("韭菜炒蛤蜊", [cu["other"], m["lunch"], m["dinner"], f["seafood"], f["stirfry"], d["main"], h["high_protein"], a["shellfish"]]),
        M("剁椒蒸鱼", [cu["xiang"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["fish"], a["chili"]]),
        M("盐烤鱼", [cu["japanese"], m["lunch"], m["dinner"], f["seafood"], f["bbq"], d["main"], h["high_protein"], a["fish"]]),
        M("蒸鱼头", [cu["yue"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], h["light"], a["fish"], a["ginger"]]),
        M("椒盐鱼骨", [cu["yue"], m["lunch"], m["dinner"], m["midnight"], f["seafood"], d["snack"], h["high_protein"], a["fish"]]),
        
        # === 更多汤类 ===
        M("豆腐鱼头汤", [cu["yue"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["nourishing"], a["fish"], a["soy"]]),
        M("菌菇汤", [cu["yunnan"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["vegan"], h["low_fat"], h["light"]]),
        M("山药排骨汤", [cu["yue"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["nourishing"], a["pork"]]),
        M("海带排骨汤", [cu["yue"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["low_fat"], a["pork"]]),
        M("冬瓜老鸭汤", [cu["yue"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["nourishing"], h["low_fat"]]),
        M("山药鸡汤", [cu["yue"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["nourishing"], h["high_protein"]]),
        M("虫草花鸡汤", [cu["yue"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["nourishing"], h["high_protein"]]),
        M("花胶鸡汤", [cu["yue"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["nourishing"], h["high_protein"]]),
        M("鱼丸汤", [cu["min"], m["lunch"], m["dinner"], f["soup"], d["soup"], a["fish"]]),
        M("贡丸汤", [cu["min"], m["lunch"], m["dinner"], f["soup"], d["soup"], a["pork"]]),
        M("蛋花汤", [cu["other"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["low_fat"], a["egg"]]),
        M("白菜豆腐汤", [cu["other"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["vegan"], h["low_fat"], h["light"], a["soy"]]),
        M("菠菜豆腐汤", [cu["other"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["vegan"], h["low_fat"], h["light"], a["soy"]]),
        M("西红柿豆腐汤", [cu["other"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["vegan"], h["low_fat"], h["light"], a["soy"]]),
        M("丝瓜汤", [cu["yue"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["vegan"], h["low_fat"], h["light"]]),
        M("冬瓜汤", [cu["yue"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["vegan"], h["low_fat"], h["light"]]),
        M("萝卜汤", [cu["other"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["vegan"], h["low_fat"], h["light"]]),
        M("绿豆百合汤", [cu["other"], m["afternoon"], f["soup"], d["beverage"], h["vegan"], h["low_fat"]]),
        M("红豆薏米汤", [cu["other"], m["afternoon"], f["soup"], d["beverage"], h["vegan"], h["low_fat"]]),
        M("姜汁撞奶", [cu["yue"], m["afternoon"], f["dessert"], d["dessert"], a["dairy"], a["ginger"]]),
        
        # === 更多凉菜 ===
        M("凉拌海带丝", [cu["other"], m["lunch"], m["dinner"], f["cold"], f["veg"], d["appetizer"], h["vegan"], h["low_fat"], h["light"], a["garlic"]]),
        M("凉拌藕片", [cu["hubei"], m["lunch"], m["dinner"], f["cold"], f["veg"], d["appetizer"], h["vegan"], h["low_fat"], h["light"], a["chili"]]),
        M("凉拌豆皮", [cu["other"], m["lunch"], m["dinner"], f["cold"], f["veg"], d["appetizer"], h["vegan"], a["soy"]]),
        M("凉拌腐竹", [cu["other"], m["lunch"], m["dinner"], f["cold"], f["veg"], d["appetizer"], h["vegan"], a["soy"], a["chili"]]),
        M("凉拌金针菇", [cu["other"], m["lunch"], m["dinner"], f["cold"], f["veg"], d["appetizer"], h["vegan"], h["low_fat"], h["light"], a["chili"]]),
        M("凉拌皮蛋", [cu["other"], m["lunch"], m["dinner"], f["cold"], d["appetizer"], a["egg"], a["garlic"]]),
        M("凉拌茄子", [cu["chuan"], m["lunch"], m["dinner"], f["cold"], f["veg"], d["appetizer"], h["vegan"], a["garlic"], a["chili"]]),
        M("凉拌西红柿", [cu["other"], m["lunch"], m["dinner"], f["cold"], f["veg"], d["appetizer"], h["vegan"], h["low_fat"]]),
        M("凉拌萝卜丝", [cu["other"], m["lunch"], m["dinner"], f["cold"], f["veg"], d["appetizer"], h["vegan"], h["low_fat"]]),
        M("凉拌豆芽", [cu["other"], m["lunch"], m["dinner"], f["cold"], f["veg"], d["appetizer"], h["vegan"], h["low_fat"], a["chili"]]),
        M("凉拌鸡丝", [cu["chuan"], m["lunch"], m["dinner"], f["cold"], f["poultry"], d["appetizer"], h["high_protein"], a["chili"], a["sesame"]]),
        M("凉拌猪耳", [cu["chuan"], m["lunch"], m["dinner"], f["cold"], f["pork"], d["appetizer"], a["pork"], a["chili"]]),
        M("凉拌猪肚", [cu["chuan"], m["lunch"], m["dinner"], f["cold"], f["pork"], d["appetizer"], a["pork"], a["chili"]]),
        M("凉拌猪头肉", [cu["chuan"], m["lunch"], m["dinner"], f["cold"], f["pork"], d["appetizer"], a["pork"], a["chili"]]),
        M("凉拌兔丁", [cu["chuan"], m["lunch"], m["dinner"], f["cold"], f["meat"], d["appetizer"], h["high_protein"], a["chili"], a["peanut"]]),
        M("蒜泥黄瓜", [cu["other"], m["lunch"], m["dinner"], f["cold"], f["veg"], d["appetizer"], h["vegan"], h["low_fat"], a["garlic"]]),
        M("糖拌西红柿", [cu["other"], m["lunch"], m["dinner"], f["cold"], f["veg"], d["appetizer"], h["vegan"]]),
        M("老虎菜", [cu["dongbei"], m["lunch"], m["dinner"], f["cold"], f["veg"], d["appetizer"], h["vegan"], a["chili"], a["onion"]]),
        M("芥末木耳", [cu["other"], m["lunch"], m["dinner"], f["cold"], f["veg"], d["appetizer"], h["vegan"], h["high_fiber"], a["mustard"]]),
        M("蒜泥茄子", [cu["dongbei"], m["lunch"], m["dinner"], f["cold"], f["veg"], d["appetizer"], h["vegan"], a["garlic"]]),
        M("口水茄子", [cu["chuan"], m["lunch"], m["dinner"], f["cold"], f["veg"], d["appetizer"], h["vegan"], a["chili"], a["sesame"]]),
        
        # === 更多火锅/烧烤 ===
        M("肥牛火锅", [cu["other"], m["lunch"], m["dinner"], f["beef"], f["hotpot"], d["main"], h["high_protein"]]),
        M("羊肉火锅", [cu["northwest"], m["lunch"], m["dinner"], f["lamb"], f["hotpot"], d["main"], h["high_protein"], h["nourishing"]]),
        M("海鲜火锅", [cu["yue"], m["lunch"], m["dinner"], f["seafood"], f["hotpot"], d["main"], h["high_protein"], a["shellfish"]]),
        M("菌菇火锅", [cu["yunnan"], m["lunch"], m["dinner"], f["veg"], f["hotpot"], d["main"], h["vegan"]]),
        M("鸳鸯火锅", [cu["chongqing"], m["lunch"], m["dinner"], m["midnight"], f["hotpot"], d["main"], a["chili"]]),
        M("九宫格火锅", [cu["chongqing"], m["lunch"], m["dinner"], m["midnight"], f["hotpot"], d["main"], a["chili"]]),
        M("潮汕牛肉火锅", [cu["yue"], m["lunch"], m["dinner"], f["beef"], f["hotpot"], d["main"], h["high_protein"]]),
        M("羊肉涮锅", [cu["beijing"], m["lunch"], m["dinner"], f["lamb"], f["hotpot"], d["main"], h["high_protein"]]),
        M("烤羊腿", [cu["xinjiang"], m["lunch"], m["dinner"], m["midnight"], f["lamb"], f["bbq"], d["main"], h["high_protein"], a["chili"]]),
        M("烤羊腰", [cu["xinjiang"], m["midnight"], f["lamb"], f["bbq"], d["snack"], a["chili"]]),
        M("烤牛板筋", [cu["other"], m["midnight"], f["beef"], f["bbq"], d["snack"], h["high_protein"], a["chili"]]),
        M("烤蚕蛹", [cu["dongbei"], m["midnight"], f["bbq"], d["snack"], h["high_protein"]]),
        M("烤鸡胗", [cu["other"], m["midnight"], f["poultry"], f["bbq"], d["snack"], h["high_protein"]]),
        M("烤鸡心", [cu["other"], m["midnight"], f["poultry"], f["bbq"], d["snack"], h["high_protein"]]),
        M("烤鱼豆腐", [cu["other"], m["afternoon"], m["midnight"], f["bbq"], d["snack"], a["soy"], a["fish"]]),
        M("烤鱼丸", [cu["other"], m["afternoon"], m["midnight"], f["bbq"], d["snack"], a["fish"]]),
        M("烤肠", [cu["other"], m["afternoon"], m["midnight"], f["pork"], f["bbq"], d["snack"], a["pork"]]),
        M("烤火腿肠", [cu["other"], m["afternoon"], m["midnight"], f["pork"], f["bbq"], d["snack"], a["pork"]]),
        
        # === 更多面食/主食 ===
        M("牛肉板面", [cu["anhui"], m["breakfast"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"], a["chili"]]),
        M("鸡蛋面", [cu["other"], m["breakfast"], m["lunch"], f["noodles"], d["staple"], a["gluten"], a["egg"]]),
        M("西红柿鸡蛋面", [cu["other"], m["breakfast"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"], a["egg"]]),
        M("雪菜肉丝面", [cu["zhe"], m["breakfast"], m["lunch"], f["noodles"], d["staple"], a["gluten"], a["pork"]]),
        M("大排面", [cu["shanghai"], m["breakfast"], m["lunch"], f["noodles"], d["staple"], a["gluten"], a["pork"]]),
        M("辣肉面", [cu["shanghai"], m["breakfast"], m["lunch"], f["noodles"], d["staple"], a["gluten"], a["pork"], a["chili"]]),
        M("大肠面", [cu["shanghai"], m["breakfast"], m["lunch"], f["noodles"], d["staple"], a["gluten"], a["pork"]]),
        M("黄鱼面", [cu["shanghai"], m["breakfast"], m["lunch"], f["noodles"], d["staple"], a["gluten"], a["fish"]]),
        M("牛蛙面", [cu["shanghai"], m["breakfast"], m["lunch"], f["noodles"], d["staple"], a["gluten"]]),
        M("鳝丝面", [cu["shanghai"], m["breakfast"], m["lunch"], f["noodles"], d["staple"], a["gluten"], a["fish"]]),
        M("担担面", [cu["chuan"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"], a["chili"], a["sesame"], a["pork"]]),
        M("甜水面", [cu["chuan"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"], a["chili"]]),
        M("豆花面", [cu["chuan"], m["breakfast"], m["lunch"], f["noodles"], d["staple"], a["gluten"], a["soy"]]),
        M("铺盖面", [cu["chongqing"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"]]),
        M("燃面", [cu["chuan"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"], a["chili"], a["peanut"]]),
        M("肥肠粉", [cu["chuan"], m["lunch"], m["dinner"], f["noodles"], d["snack"], a["chili"], a["pork"]]),
        M("酸辣粉(重庆)", [cu["chongqing"], m["lunch"], m["dinner"], m["midnight"], f["noodles"], d["snack"], a["chili"], a["gluten"]]),
        M("花甲粉", [cu["other"], m["lunch"], m["dinner"], m["midnight"], f["noodles"], d["snack"], a["shellfish"], a["chili"]]),
        M("土豆粉", [cu["other"], m["lunch"], m["dinner"], f["noodles"], d["snack"], a["chili"]]),
        M("鱼粉", [cu["xiang"], m["lunch"], m["dinner"], f["noodles"], d["snack"], a["fish"], a["chili"]]),
        M("番茄鸡蛋盖饭", [cu["other"], m["lunch"], m["dinner"], f["rice"], d["staple"], a["egg"]]),
        M("鱼香肉丝盖饭", [cu["chuan"], m["lunch"], m["dinner"], f["rice"], d["staple"], a["pork"], a["chili"]]),
        M("宫保鸡丁盖饭", [cu["chuan"], m["lunch"], m["dinner"], f["rice"], d["staple"], h["high_protein"], a["peanut"], a["chili"]]),
        M("麻婆豆腐盖饭", [cu["chuan"], m["lunch"], m["dinner"], f["rice"], d["staple"], h["vegan"], a["soy"], a["chili"]]),
        M("回锅肉盖饭", [cu["chuan"], m["lunch"], m["dinner"], f["rice"], d["staple"], a["pork"], a["chili"]]),
        M("糖醋里脊盖饭", [cu["lu"], m["lunch"], m["dinner"], f["rice"], d["staple"], a["pork"]]),
        M("土豆牛肉盖饭", [cu["other"], m["lunch"], m["dinner"], f["rice"], d["staple"], h["high_protein"]]),
        M("红烧肉盖饭", [cu["other"], m["lunch"], m["dinner"], f["rice"], d["staple"], a["pork"], a["soy"]]),
        M("咖喱鸡肉饭", [cu["indian"], m["lunch"], m["dinner"], f["rice"], d["staple"], h["high_protein"], a["dairy"]]),
        M("咖喱牛肉饭", [cu["indian"], m["lunch"], m["dinner"], f["rice"], d["staple"], h["high_protein"], a["dairy"]]),
        M("牛丼", [cu["japanese"], m["lunch"], m["dinner"], f["rice"], d["staple"], h["high_protein"], a["soy"]]),
        M("亲子丼", [cu["japanese"], m["lunch"], m["dinner"], f["rice"], d["staple"], h["high_protein"], a["egg"]]),
        M("滑蛋牛肉饭", [cu["yue"], m["lunch"], m["dinner"], f["rice"], d["staple"], h["high_protein"], a["egg"]]),
        M("滑蛋虾仁饭", [cu["yue"], m["lunch"], m["dinner"], f["rice"], d["staple"], h["high_protein"], a["shellfish"], a["egg"]]),
        M("杂粮煎饼", [cu["lu"], m["breakfast"], f["pancake"], d["staple"], h["high_fiber"], a["gluten"]]),
        M("煎饼卷大葱", [cu["lu"], m["breakfast"], m["lunch"], f["pancake"], d["staple"], a["gluten"], a["onion"]]),
        M("烤冷面卷臭豆腐", [cu["dongbei"], m["afternoon"], m["midnight"], f["snack"], d["snack"], a["gluten"], a["egg"], a["soy"]]),
        M("驴肉火烧", [cu["other"], m["breakfast"], m["lunch"], f["pancake"], d["snack"], a["gluten"]]),
        M("羊肉火烧", [cu["northwest"], m["breakfast"], m["lunch"], f["pancake"], d["snack"], a["gluten"]]),
        
        # === 更多地方特色 ===
        M("西湖莼菜汤", [cu["zhe"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["vegan"], h["low_fat"], h["light"]]),
        M("宋嫂鱼羹", [cu["zhe"], m["lunch"], m["dinner"], f["soup"], d["soup"], a["fish"]]),
        M("干炸响铃", [cu["zhe"], m["lunch"], m["dinner"], f["veg"], d["snack"], a["soy"], a["gluten"]]),
        M("葱包烩", [cu["zhe"], m["breakfast"], m["lunch"], f["snack"], d["snack"], a["gluten"], a["onion"]]),
        M("定胜糕", [cu["zhe"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"]]),
        M("条头糕", [cu["shanghai"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"], a["soy"]]),
        M("青团", [cu["shanghai"], m["afternoon"], m["breakfast"], f["dessert"], d["dessert"], a["gluten"], a["soy"]]),
        M("蟹壳黄", [cu["shanghai"], m["afternoon"], m["breakfast"], f["dessert"], d["dessert"], a["gluten"], a["sesame"]]),
        M("鸡仔饼", [cu["yue"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"], a["pork"]]),
        M("杏仁饼", [cu["yue"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"], a["tree_nut"]]),
        M("盲公饼", [cu["yue"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"], a["peanut"]]),
        M("猪油糕", [cu["yue"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"], a["pork"]]),
        M("钵仔糕", [cu["yue"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"]]),
        M("伦教糕", [cu["yue"], m["afternoon"], m["breakfast"], f["dessert"], d["dessert"], a["gluten"]]),
        M("肠粉(潮汕)", [cu["yue"], m["breakfast"], m["lunch"], f["snack"], d["snack"], a["gluten"]]),
        M("蚝烙", [cu["yue"], m["lunch"], m["dinner"], f["seafood"], d["snack"], a["shellfish"], a["egg"], a["gluten"]]),
        M("沙茶面", [cu["min"], m["breakfast"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"], a["shellfish"]]),
        M("面线糊", [cu["min"], m["breakfast"], m["lunch"], f["noodles"], d["snack"], a["gluten"]]),
        M("五香卷", [cu["min"], m["lunch"], m["dinner"], f["pork"], d["snack"], a["pork"], a["gluten"]]),
        M("闽南炸醋肉", [cu["min"], m["lunch"], m["dinner"], f["pork"], d["snack"], a["pork"], a["gluten"]]),
        M("福州鱼丸", [cu["min"], m["lunch"], m["dinner"], f["seafood"], d["snack"], a["fish"]]),
        M("莆田卤面", [cu["min"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"], a["shellfish"]]),
        M("厦门沙茶面", [cu["min"], m["breakfast"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"], a["shellfish"]]),
        M("土笋冻", [cu["min"], m["lunch"], m["dinner"], f["cold"], d["snack"], a["shellfish"]]),
        M("客家酿豆腐", [cu["yue"], m["lunch"], m["dinner"], f["veg"], d["main"], h["high_protein"], a["soy"], a["pork"]]),
        M("客家盐焗鸡", [cu["yue"], m["lunch"], m["dinner"], f["poultry"], d["main"], h["high_protein"]]),
        M("客家梅菜扣肉", [cu["yue"], m["lunch"], m["dinner"], f["pork"], d["main"], a["pork"], a["soy"]]),
        M("坛子肉", [cu["xiang"], m["lunch"], m["dinner"], f["pork"], d["main"], a["pork"], a["chili"]]),
        M("血鸭", [cu["xiang"], m["lunch"], m["dinner"], f["poultry"], d["main"], h["high_protein"], a["chili"]]),
        M("东安鸡", [cu["xiang"], m["lunch"], m["dinner"], f["poultry"], d["main"], h["high_protein"], a["chili"]]),
        M("安乡鸭", [cu["xiang"], m["lunch"], m["dinner"], f["poultry"], d["main"], h["high_protein"], a["chili"]]),
        M("常德酱板鸭", [cu["xiang"], m["lunch"], m["dinner"], m["afternoon"], f["poultry"], d["snack"], a["chili"], a["soy"]]),
        M("临武鸭", [cu["xiang"], m["lunch"], m["dinner"], m["afternoon"], f["poultry"], d["snack"], a["chili"]]),
        M("湘西土匪鸭", [cu["xiang"], m["lunch"], m["dinner"], f["poultry"], d["main"], h["high_protein"], a["chili"]]),
        M("麻仁香酥鸭", [cu["xiang"], m["lunch"], m["dinner"], f["poultry"], d["main"], h["high_protein"], a["sesame"]]),
        M("衡阳鱼粉", [cu["xiang"], m["breakfast"], m["lunch"], f["noodles"], d["snack"], a["fish"], a["chili"]]),
        M("邵阳米粉", [cu["xiang"], m["breakfast"], m["lunch"], f["noodles"], d["snack"], a["chili"]]),
        M("襄阳牛肉面", [cu["hubei"], m["breakfast"], m["lunch"], f["noodles"], d["staple"], h["high_protein"], a["gluten"], a["chili"]]),
        M("荆州鱼糕", [cu["hubei"], m["lunch"], m["dinner"], f["seafood"], d["main"], a["fish"]]),
        M("黄陂三合", [cu["hubei"], m["lunch"], m["dinner"], f["meat"], d["main"], a["fish"], a["pork"]]),
        M("红烧鮰鱼", [cu["hubei"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["fish"]]),
        M("洛阳水席", [cu["henan"], m["lunch"], m["dinner"], f["soup"], d["soup"], a["chili"]]),
        M("开封灌汤包", [cu["henan"], m["breakfast"], m["lunch"], f["bun"], d["snack"], a["gluten"], a["pork"]]),
        M("道口烧鸡", [cu["henan"], m["lunch"], m["dinner"], f["poultry"], d["main"], h["high_protein"]]),
        M("逍遥镇胡辣汤", [cu["henan"], m["breakfast"], f["soup"], d["soup"], a["chili"], a["gluten"]]),
        M("羊肉烩面", [cu["henan"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"]]),
        M("陕西凉皮", [cu["shaanxi"], m["lunch"], m["dinner"], f["cold"], d["snack"], a["gluten"], a["chili"], a["garlic"]]),
        M("岐山臊子面", [cu["shaanxi"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"], a["chili"], a["pork"]]),
        M("葫芦头", [cu["shaanxi"], m["lunch"], m["dinner"], f["pork"], d["snack"], a["pork"], a["gluten"]]),
        M("灌汤包子", [cu["shaanxi"], m["breakfast"], m["lunch"], f["bun"], d["snack"], a["gluten"], a["pork"]]),
        M("甑糕", [cu["shaanxi"], m["breakfast"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"]]),
        M("兰新拉面", [cu["gansu"], m["breakfast"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"]]),
        M("牛奶鸡蛋醪糟", [cu["gansu"], m["breakfast"], m["afternoon"], f["dessert"], d["dessert"], a["dairy"], a["egg"]]),
        M("洋芋搅团", [cu["gansu"], m["lunch"], m["dinner"], f["veg"], d["snack"], h["vegan"]]),
        M("酸汤水饺", [cu["shaanxi"], m["lunch"], m["dinner"], f["dumpling"], d["staple"], a["gluten"], a["chili"]]),
        M("金线油塔", [cu["shaanxi"], m["breakfast"], m["lunch"], f["noodles"], d["snack"], a["gluten"]]),
        M("蓼花糖", [cu["shaanxi"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"], a["sesame"]]),
        M("石子馍", [cu["shaanxi"], m["breakfast"], m["afternoon"], f["pancake"], d["snack"], a["gluten"]]),
        M("锅盔", [cu["shaanxi"], m["breakfast"], m["lunch"], f["pancake"], d["staple"], a["gluten"]]),
        M("油茶", [cu["northwest"], m["breakfast"], f["tea"], d["beverage"], a["peanut"], a["sesame"]]),
        M("拉条子", [cu["xinjiang"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"]]),
        M("丁丁炒面", [cu["xinjiang"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"]]),
        M("抓饭", [cu["xinjiang"], m["lunch"], m["dinner"], f["rice"], d["staple"]]),
        M("新疆炒米粉", [cu["xinjiang"], m["lunch"], m["dinner"], f["noodles"], d["snack"], a["chili"]]),
        M("烤包子(新疆)", [cu["xinjiang"], m["breakfast"], m["lunch"], f["bun"], d["snack"], a["gluten"]]),
        M("馕", [cu["xinjiang"], m["breakfast"], m["lunch"], m["dinner"], f["pancake"], d["staple"], a["gluten"], a["sesame"]]),
        M("红柳烤肉", [cu["xinjiang"], m["lunch"], m["dinner"], m["midnight"], f["lamb"], f["bbq"], d["snack"], h["high_protein"], a["chili"]]),
        M("米粉(贵州)", [cu["guizhou"], m["breakfast"], m["lunch"], m["dinner"], f["noodles"], d["snack"], a["chili"]]),
        M("肠旺面", [cu["guizhou"], m["breakfast"], m["lunch"], f["noodles"], d["staple"], a["gluten"], a["chili"], a["pork"]]),
        M("丝娃娃", [cu["guizhou"], m["lunch"], m["dinner"], f["veg"], d["snack"], a["chili"]]),
        M("青岩卤猪脚", [cu["guizhou"], m["lunch"], m["dinner"], f["pork"], d["snack"], a["pork"], a["soy"]]),
        M("凯里酸汤鱼", [cu["guizhou"], m["lunch"], m["dinner"], f["seafood"], d["main"], h["high_protein"], a["fish"], a["chili"]]),
        M("折耳根炒腊肉", [cu["guizhou"], m["lunch"], m["dinner"], f["pork"], f["stirfry"], d["main"], a["pork"], a["chili"]]),
        M("贵阳糯米饭", [cu["guizhou"], m["breakfast"], m["lunch"], f["rice"], d["staple"], a["chili"]]),
        M("云南过桥米线", [cu["yunnan"], m["breakfast"], m["lunch"], m["dinner"], f["noodles"], d["staple"], h["high_protein"]]),
        M("饵块", [cu["yunnan"], m["breakfast"], m["lunch"], f["rice"], d["staple"], a["chili"]]),
        M("饵丝", [cu["yunnan"], m["breakfast"], m["lunch"], f["rice"], d["staple"], a["chili"]]),
        M("豆花米线", [cu["yunnan"], m["breakfast"], m["lunch"], f["noodles"], d["snack"], a["chili"], a["soy"]]),
        M("小锅米线", [cu["yunnan"], m["breakfast"], m["lunch"], f["noodles"], d["snack"], a["chili"]]),
        M("宣威火腿", [cu["yunnan"], m["lunch"], m["dinner"], f["pork"], d["main"], a["pork"]]),
        M("菠萝饭", [cu["yunnan"], m["lunch"], m["dinner"], f["rice"], d["staple"]]),
        M("竹筒饭", [cu["yunnan"], m["lunch"], m["dinner"], f["rice"], d["staple"]]),
        M("香茅草烤鱼", [cu["yunnan"], m["lunch"], m["dinner"], f["seafood"], f["bbq"], d["main"], h["high_protein"], a["fish"]]),
        M("榕江卷粉", [cu["guizhou"], m["breakfast"], m["lunch"], f["snack"], d["snack"], a["chili"]]),
        M("酸嘢", [cu["guangxi"], m["afternoon"], m["lunch"], f["snack"], d["snack"], a["chili"]]),
        M("龟苓膏(梧州)", [cu["guangxi"], m["afternoon"], f["dessert"], d["dessert"]]),
        M("玉林牛巴", [cu["guangxi"], m["lunch"], m["dinner"], f["beef"], d["snack"], a["chili"], a["soy"]]),
        M("柠檬鸭", [cu["guangxi"], m["lunch"], m["dinner"], f["poultry"], d["main"], h["high_protein"], a["chili"]]),
        M("桂林米粉(卤菜)", [cu["guangxi"], m["breakfast"], m["lunch"], m["dinner"], f["noodles"], d["snack"], a["chili"], a["peanut"]]),
        M("南宁老友粉", [cu["guangxi"], m["breakfast"], m["lunch"], m["dinner"], f["noodles"], d["snack"], a["chili"], a["soy"]]),
        M("螺蛳鸭脚煲", [cu["guangxi"], m["lunch"], m["dinner"], m["midnight"], f["poultry"], f["stew"], d["main"], a["chili"]]),
        M("清补凉", [cu["other"], m["afternoon"], f["dessert"], d["dessert"], h["low_fat"]]),
        M("陵水酸粉", [cu["other"], m["breakfast"], m["lunch"], f["noodles"], d["snack"], a["chili"]]),
        M("抱罗粉", [cu["other"], m["breakfast"], m["lunch"], f["noodles"], d["snack"], a["chili"]]),
        M("烤乳猪", [cu["other"], m["lunch"], m["dinner"], f["pork"], d["main"], a["pork"]]),
        M("三杯鸡", [cu["min"], m["lunch"], m["dinner"], f["poultry"], d["main"], h["high_protein"], a["soy"], a["garlic"]]),
        M("姜母鸭", [cu["min"], m["lunch"], m["dinner"], f["poultry"], d["main"], h["high_protein"], h["nourishing"], a["ginger"]]),
        M("烧肉粽", [cu["min"], m["breakfast"], m["lunch"], f["rice"], d["snack"], a["pork"], a["gluten"]]),
        M("面线糊(泉州)", [cu["min"], m["breakfast"], m["lunch"], f["noodles"], d["snack"], a["gluten"]]),
        M("同安封肉", [cu["min"], m["lunch"], m["dinner"], f["pork"], d["main"], a["pork"]]),
        M("漳州卤面", [cu["min"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"], a["shellfish"]]),
        M("福鼎肉片", [cu["min"], m["lunch"], m["dinner"], m["midnight"], f["pork"], d["snack"], a["pork"], a["gluten"]]),
        M("安徽板面", [cu["anhui"], m["breakfast"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"], a["chili"]]),
        M("黄山烧饼", [cu["anhui"], m["breakfast"], m["afternoon"], f["pancake"], d["snack"], a["gluten"], a["pork"]]),
        M("淮南牛肉汤", [cu["anhui"], m["breakfast"], m["lunch"], m["dinner"], f["soup"], d["soup"], h["high_protein"], h["nourishing"]]),
        M("符离集烧鸡", [cu["anhui"], m["lunch"], m["dinner"], f["poultry"], d["main"], h["high_protein"]]),
        M("绩溪炒粉丝", [cu["anhui"], m["lunch"], m["dinner"], f["noodles"], d["staple"], a["gluten"]]),
        
        # === 饮品 ===
        M("美式咖啡", [cu["american"], m["breakfast"], m["afternoon"], f["coffee"], d["beverage"], h["low_cal"]]),
        M("拿铁", [cu["italian"], m["breakfast"], m["afternoon"], f["coffee"], d["beverage"], a["dairy"]]),
        M("卡布奇诺", [cu["italian"], m["breakfast"], m["afternoon"], f["coffee"], d["beverage"], a["dairy"]]),
        M("摩卡", [cu["italian"], m["breakfast"], m["afternoon"], f["coffee"], d["beverage"], a["dairy"]]),
        M("抹茶拿铁", [cu["japanese"], m["breakfast"], m["afternoon"], f["coffee"], d["beverage"], a["dairy"]]),
        M("冰美式", [cu["american"], m["breakfast"], m["afternoon"], f["coffee"], d["beverage"], h["low_cal"]]),
        M("冷萃咖啡", [cu["american"], m["breakfast"], m["afternoon"], f["coffee"], d["beverage"], h["low_cal"]]),
        M("绿茶", [cu["other"], m["lunch"], m["afternoon"], f["tea"], d["beverage"], h["low_cal"]]),
        M("红茶", [cu["other"], m["lunch"], m["afternoon"], f["tea"], d["beverage"], h["low_cal"]]),
        M("乌龙茶", [cu["min"], m["lunch"], m["afternoon"], f["tea"], d["beverage"], h["low_cal"]]),
        M("普洱茶", [cu["yunnan"], m["lunch"], m["afternoon"], f["tea"], d["beverage"], h["low_cal"]]),
        M("茉莉花茶", [cu["beijing"], m["lunch"], m["afternoon"], f["tea"], d["beverage"], h["low_cal"]]),
        M("菊花茶", [cu["other"], m["lunch"], m["afternoon"], f["tea"], d["beverage"], h["low_cal"]]),
        M("大麦茶", [cu["other"], m["lunch"], m["afternoon"], f["tea"], d["beverage"], h["low_cal"]]),
        M("桂花茶", [cu["zhe"], m["lunch"], m["afternoon"], f["tea"], d["beverage"], h["low_cal"]]),
        M("玫瑰花茶", [cu["other"], m["lunch"], m["afternoon"], f["tea"], d["beverage"], h["low_cal"]]),
        M("蜂蜜柚子茶", [cu["other"], m["afternoon"], f["fruit_tea"], d["beverage"]]),
        M("百香果茶", [cu["other"], m["afternoon"], f["fruit_tea"], d["beverage"]]),
        M("芒果冰沙", [cu["other"], m["afternoon"], f["fruit_tea"], d["beverage"]]),
        M("草莓奶昔", [cu["american"], m["afternoon"], f["fruit_tea"], d["beverage"], a["dairy"]]),
        M("啤酒", [cu["german"], m["dinner"], m["midnight"], f["alcohol"], d["beverage"], a["gluten"]]),
        M("白酒", [cu["other"], m["dinner"], m["midnight"], f["alcohol"], d["beverage"]]),
        M("红酒", [cu["french"], m["dinner"], f["alcohol"], d["beverage"], a["sulfite"]]),
        M("黄酒", [cu["zhe"], m["dinner"], f["alcohol"], d["beverage"]]),
        M("米酒", [cu["other"], m["dinner"], f["alcohol"], d["beverage"], a["gluten"]]),
        M("清酒", [cu["japanese"], m["dinner"], f["alcohol"], d["beverage"]]),
        M("烧酒", [cu["korean"], m["dinner"], m["midnight"], f["alcohol"], d["beverage"]]),
        M("梅酒", [cu["japanese"], m["dinner"], m["afternoon"], f["alcohol"], d["beverage"]]),
        M("鸡尾酒", [cu["american"], m["dinner"], m["midnight"], f["alcohol"], d["beverage"]]),
        M("柠檬水", [cu["other"], m["afternoon"], m["lunch"], f["fruit_tea"], d["beverage"], h["low_cal"]]),
        M("椰子水", [cu["other"], m["afternoon"], f["fruit_tea"], d["beverage"], h["low_cal"]]),
        M("甘蔗汁", [cu["yue"], m["afternoon"], f["fruit_tea"], d["beverage"]]),
        M("薏米水", [cu["other"], m["afternoon"], f["tea"], d["beverage"], h["low_cal"]]),
        M("凉茶", [cu["yue"], m["afternoon"], m["lunch"], f["tea"], d["beverage"], h["low_cal"]]),
        M("王老吉", [cu["yue"], m["afternoon"], m["lunch"], f["tea"], d["beverage"]]),
        M("加多宝", [cu["yue"], m["afternoon"], m["lunch"], f["tea"], d["beverage"]]),
        M("元气森林", [cu["other"], m["afternoon"], f["fruit_tea"], d["beverage"], h["low_cal"]]),
        M("气泡水", [cu["other"], m["afternoon"], f["fruit_tea"], d["beverage"], h["low_cal"]]),
        M("格瓦斯", [cu["other"], m["afternoon"], m["lunch"], f["alcohol"], d["beverage"], a["gluten"]]),
        M("冰峰", [cu["shaanxi"], m["afternoon"], m["lunch"], f["fruit_tea"], d["beverage"]]),
        M("北冰洋", [cu["beijing"], m["afternoon"], m["lunch"], f["fruit_tea"], d["beverage"]]),
        
        # === 更多杂项 ===
        M("八宝粥", [cu["other"], m["breakfast"], m["afternoon"], f["congee"], d["staple"], h["vegan"], h["high_fiber"]]),
        M("小米粥", [cu["other"], m["breakfast"], m["afternoon"], f["congee"], d["staple"], h["vegan"], h["low_fat"], h["light"]]),
        M("南瓜粥", [cu["other"], m["breakfast"], m["afternoon"], f["congee"], d["staple"], h["vegan"], h["low_fat"]]),
        M("皮蛋瘦肉粥", [cu["yue"], m["breakfast"], m["lunch"], f["congee"], d["staple"], a["egg"], a["pork"]]),
        M("海鲜粥", [cu["yue"], m["breakfast"], m["lunch"], f["congee"], d["staple"], a["shellfish"], a["fish"]]),
        M("及第粥", [cu["yue"], m["breakfast"], m["lunch"], f["congee"], d["staple"], a["pork"]]),
        M("艇仔粥", [cu["yue"], m["breakfast"], m["lunch"], f["congee"], d["staple"], a["shellfish"], a["fish"], a["peanut"]]),
        M("潮汕砂锅粥", [cu["yue"], m["lunch"], m["dinner"], f["congee"], d["staple"], a["shellfish"]]),
        M("白粥", [cu["other"], m["breakfast"], m["lunch"], f["congee"], d["staple"], h["vegan"], h["low_fat"], h["light"]]),
        M("紫米粥", [cu["other"], m["breakfast"], m["afternoon"], f["congee"], d["staple"], h["vegan"], h["high_fiber"]]),
        M("燕麦粥", [cu["western"], m["breakfast"], f["congee"], d["staple"], h["high_fiber"], h["vegan"]]),
        M("红薯粥", [cu["other"], m["breakfast"], m["afternoon"], f["congee"], d["staple"], h["vegan"], h["high_fiber"]]),
        M("玉米粥", [cu["other"], m["breakfast"], m["afternoon"], f["congee"], d["staple"], h["vegan"], h["high_fiber"]]),
        M("干锅鸡", [cu["chuan"], m["lunch"], m["dinner"], f["poultry"], f["stirfry"], d["main"], h["high_protein"], a["chili"]]),
        M("干锅虾", [cu["chuan"], m["lunch"], m["dinner"], f["seafood"], f["stirfry"], d["main"], h["high_protein"], a["shellfish"], a["chili"]]),
        M("干锅排骨", [cu["chuan"], m["lunch"], m["dinner"], f["pork"], f["stirfry"], d["main"], a["pork"], a["chili"]]),
        M("干锅千页豆腐", [cu["chuan"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], a["soy"], a["chili"]]),
        M("铁板豆腐", [cu["other"], m["lunch"], m["dinner"], f["veg"], d["main"], h["vegan"], a["soy"]]),
        M("铁板鱿鱼须", [cu["other"], m["afternoon"], m["midnight"], f["seafood"], d["snack"], a["shellfish"], a["chili"]]),
        M("铁板肥牛", [cu["other"], m["lunch"], m["dinner"], f["beef"], d["main"], h["high_protein"], a["onion"]]),
        M("牛肉锅贴", [cu["other"], m["breakfast"], m["lunch"], f["dumpling"], d["snack"], h["high_protein"], a["gluten"]]),
        M("韭菜鸡蛋饺子", [cu["dongbei"], m["lunch"], m["dinner"], f["dumpling"], d["staple"], a["gluten"], a["egg"]]),
        M("白菜猪肉饺子", [cu["dongbei"], m["lunch"], m["dinner"], f["dumpling"], d["staple"], a["gluten"], a["pork"]]),
        M("芹菜猪肉饺子", [cu["dongbei"], m["lunch"], m["dinner"], f["dumpling"], d["staple"], a["gluten"], a["pork"], a["celery"]]),
        M("三鲜饺子", [cu["dongbei"], m["lunch"], m["dinner"], f["dumpling"], d["staple"], a["gluten"], a["pork"], a["shellfish"], a["egg"]]),
        M("牛肉饺子", [cu["northwest"], m["lunch"], m["dinner"], f["dumpling"], d["staple"], h["high_protein"], a["gluten"]]),
        M("羊肉饺子", [cu["northwest"], m["lunch"], m["dinner"], f["dumpling"], d["staple"], a["gluten"]]),
        M("虾仁饺子", [cu["yue"], m["lunch"], m["dinner"], f["dumpling"], d["staple"], h["high_protein"], a["gluten"], a["shellfish"]]),
        M("酸菜饺子", [cu["dongbei"], m["lunch"], m["dinner"], f["dumpling"], d["staple"], a["gluten"], a["pork"]]),
        M("茴香饺子", [cu["beijing"], m["lunch"], m["dinner"], f["dumpling"], d["staple"], a["gluten"], a["pork"]]),
        M("鱼肉饺子", [cu["lu"], m["lunch"], m["dinner"], f["dumpling"], d["staple"], a["gluten"], a["fish"]]),
        M("素三鲜饺子", [cu["other"], m["lunch"], m["dinner"], f["dumpling"], d["staple"], h["vegan"], a["gluten"]]),
        M("锅贴(猪肉)", [cu["other"], m["breakfast"], m["lunch"], f["dumpling"], d["snack"], a["gluten"], a["pork"]]),
        M("菜煎饼", [cu["lu"], m["breakfast"], m["lunch"], f["pancake"], d["staple"], h["vegan"], a["gluten"]]),
        M("玉米饼", [cu["dongbei"], m["breakfast"], m["lunch"], f["pancake"], d["staple"], h["high_fiber"], a["gluten"]]),
        M("小米饼", [cu["other"], m["breakfast"], m["lunch"], f["pancake"], d["staple"], a["gluten"]]),
        M("椒盐饼", [cu["other"], m["breakfast"], m["lunch"], f["pancake"], d["snack"], a["gluten"]]),
        M("麻酱烧饼", [cu["beijing"], m["breakfast"], m["lunch"], f["pancake"], d["snack"], a["gluten"], a["sesame"]]),
        M("油酥烧饼", [cu["beijing"], m["breakfast"], m["lunch"], f["pancake"], d["snack"], a["gluten"]]),
        M("白吉馍", [cu["shaanxi"], m["breakfast"], m["lunch"], f["pancake"], d["staple"], a["gluten"]]),
        M("鸡蛋灌饼(原味)", [cu["henan"], m["breakfast"], f["pancake"], d["staple"], a["gluten"], a["egg"]]),
        M("葱花饼", [cu["other"], m["breakfast"], m["lunch"], f["pancake"], d["snack"], a["gluten"], a["onion"]]),
        M("土豆饼", [cu["other"], m["breakfast"], m["lunch"], f["pancake"], d["snack"], h["vegan"], a["gluten"]]),
        M("南瓜饼", [cu["other"], m["breakfast"], m["afternoon"], f["pancake"], d["snack"], a["gluten"]]),
        M("紫薯饼", [cu["other"], m["afternoon"], f["pancake"], d["snack"], h["vegan"], a["gluten"]]),
        M("藕夹", [cu["hubei"], m["lunch"], m["dinner"], f["veg"], d["snack"], a["gluten"]]),
        M("糖醋藕片", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"]]),
        M("炒藕片", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], h["low_fat"]]),
        M("炒山药", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], h["low_fat"]]),
        M("炒丝瓜", [cu["yue"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], h["low_fat"], h["light"]]),
        M("炒苦瓜", [cu["yue"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], h["low_fat"]]),
        M("炒芥蓝", [cu["yue"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], h["low_fat"], h["light"]]),
        M("炒菜花", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], h["low_fat"]]),
        M("炒茼蒿", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], h["low_fat"], h["light"]]),
        M("炒油麦菜", [cu["yue"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], h["low_fat"], h["light"]]),
        M("炒娃娃菜", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], h["low_fat"], h["light"]]),
        M("炒大白菜", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], h["low_fat"], h["light"]]),
        M("炒豆角", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"]]),
        M("炒茄子", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"]]),
        M("炒土豆丝", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"]]),
        M("炒洋葱", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], a["onion"]]),
        M("炒萝卜丝", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], h["low_fat"]]),
        M("炒冬瓜", [cu["yue"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], h["low_fat"], h["light"]]),
        M("炒南瓜", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"]]),
        M("红烧茄子", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], a["soy"]]),
        M("红烧豆腐", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], h["high_protein"], a["soy"]]),
        M("红烧冬瓜", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], a["soy"]]),
        M("番茄菜花", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"]]),
        M("蒜苗炒肉", [cu["other"], m["lunch"], m["dinner"], f["pork"], f["stirfry"], d["main"], a["pork"], a["garlic"]]),
        M("芹菜炒肉", [cu["other"], m["lunch"], m["dinner"], f["pork"], f["stirfry"], d["main"], a["pork"], a["celery"]]),
        M("洋葱炒肉", [cu["other"], m["lunch"], m["dinner"], f["pork"], f["stirfry"], d["main"], a["pork"], a["onion"]]),
        M("青椒炒肉", [cu["xiang"], m["lunch"], m["dinner"], f["pork"], f["stirfry"], d["main"], a["pork"], a["chili"]]),
        M("豆角炒肉", [cu["other"], m["lunch"], m["dinner"], f["pork"], f["stirfry"], d["main"], a["pork"]]),
        M("蒜苔炒肉", [cu["other"], m["lunch"], m["dinner"], f["pork"], f["stirfry"], d["main"], a["pork"], a["garlic"]]),
        M("韭黄炒蛋", [cu["yue"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], a["egg"]]),
        M("虾仁炒蛋", [cu["yue"], m["lunch"], m["dinner"], f["seafood"], f["stirfry"], d["main"], h["high_protein"], a["shellfish"], a["egg"]]),
        M("苦瓜炒蛋", [cu["yue"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], a["egg"]]),
        M("韭菜炒蛋", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], a["egg"]]),
        M("洋葱炒蛋", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], a["egg"], a["onion"]]),
        M("丝瓜炒蛋", [cu["yue"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], a["egg"]]),
        M("西葫芦炒蛋", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], a["egg"]]),
        M("火腿炒蛋", [cu["other"], m["lunch"], m["dinner"], f["pork"], f["stirfry"], d["main"], a["pork"], a["egg"]]),
        M("木耳炒蛋", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], a["egg"]]),
        M("青椒炒蛋", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], a["egg"], a["chili"]]),
        M("秋葵炒蛋", [cu["other"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], a["egg"]]),
        M("干煸豆角", [cu["chuan"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], a["chili"]]),
        M("干煸土豆丝", [cu["chuan"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], a["chili"]]),
        M("干煸牛肉丝", [cu["chuan"], m["lunch"], m["dinner"], f["beef"], f["stirfry"], d["main"], h["high_protein"], a["chili"]]),
        M("焦溜丸子", [cu["lu"], m["lunch"], m["dinner"], f["pork"], d["main"], a["pork"]]),
        M("软炸里脊", [cu["lu"], m["lunch"], m["dinner"], f["pork"], d["main"], a["pork"], a["egg"]]),
        M("干炸里脊", [cu["lu"], m["lunch"], m["dinner"], f["pork"], d["main"], a["pork"], a["gluten"]]),
        M("烧茄子", [cu["dongbei"], m["lunch"], m["dinner"], f["veg"], f["stirfry"], d["main"], h["vegan"], a["garlic"]]),
        M("扒肉条", [cu["dongbei"], m["lunch"], m["dinner"], f["pork"], d["main"], a["pork"], a["soy"]]),
        M("雪衣豆沙", [cu["dongbei"], m["afternoon"], f["dessert"], d["dessert"], a["egg"], a["soy"], a["gluten"]]),
        M("拔丝地瓜", [cu["dongbei"], m["lunch"], m["dinner"], f["dessert"], d["dessert"], h["vegan"]]),
        M("拔丝苹果", [cu["dongbei"], m["lunch"], m["dinner"], f["dessert"], d["dessert"], h["vegan"]]),
        M("拔丝香蕉", [cu["dongbei"], m["lunch"], m["dinner"], f["dessert"], d["dessert"], h["vegan"]]),
        M("蓝莓山药", [cu["other"], m["lunch"], m["dinner"], m["afternoon"], f["dessert"], d["dessert"]]),
        M("桂花糯米藕", [cu["su"], m["lunch"], m["dinner"], m["afternoon"], f["dessert"], d["dessert"], h["vegan"]]),
        M("酒酿圆子", [cu["su"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"]]),
        M("赤豆元宵", [cu["su"], m["afternoon"], m["breakfast"], f["dessert"], d["dessert"], a["gluten"]]),
        M("糖芋苗", [cu["su"], m["afternoon"], f["dessert"], d["dessert"], h["vegan"]]),
        M("梅花糕", [cu["su"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"], a["soy"]]),
        M("海棠糕", [cu["su"], m["afternoon"], f["dessert"], d["dessert"], a["gluten"], a["soy"]]),
        M("豆腐花(甜)", [cu["yue"], m["afternoon"], f["dessert"], d["dessert"], h["vegan"], a["soy"]]),
        M("豆腐花(咸)", [cu["other"], m["breakfast"], f["snack"], d["snack"], h["vegan"], a["soy"]]),
    ]
    
    # 过滤重复
    added = 0
    skipped = 0
    for dish in new_dishes:
        name = dish["name"]
        if name in existing_names:
            skipped += 1
            continue
        max_id += 1
        item = {
            "id": f"item_{max_id:05d}",
            "name": name,
            "categories": dish["categories"],
            "attributes": {"health": [], "allergens": []}
        }
        data["items"].append(item)
        existing_names.add(name)
        added += 1
    
    print(f"新增 {added} 道，跳过 {skipped} 道（已存在）")
    print(f"总菜品数: {len(data['items'])}")
    
    # 保存
    with open(SRC_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"已保存到 {SRC_PATH}")

if __name__ == "__main__":
    main()