const fs = require('fs');
let id = 5500;
function E(n, c, h = [], a = [], s = []) {
  const e = { id: `item_${String(id).padStart(5, '0')}`, name: n, categories: c, attributes: { health: h, allergens: a } };
  if (s.length) e.attributes.searchAliases = s;
  id++; return e;
}

// ===== COMMON (全国常见, ≥3省) =====
const common = [
  // 川菜经典
  E('辣子鸡',['cuisine_chuan','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_chili'],[],[],[]),
  E('口水鸡',['cuisine_chuan','meal_lunch','meal_dinner','food_poultry','dish_appetizer','allergen_chili','allergen_peanut','allergen_sesame'],[],[],[]),
  E('棒棒鸡',['cuisine_chuan','meal_lunch','meal_dinner','food_poultry','dish_appetizer','allergen_chili','allergen_sesame'],[],[],[]),
  E('宫保鸡丁',['cuisine_chuan','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_chili','allergen_peanut'],[],[],[]),
  E('水煮牛肉',['cuisine_chuan','meal_lunch','meal_dinner','food_beef','dish_main','allergen_chili'],[],[],[]),
  E('水煮鱼片',['cuisine_chuan','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_chili','allergen_fish'],[],[],[]),
  E('水煮肉片',['cuisine_chuan','meal_lunch','meal_dinner','food_pork','dish_main','allergen_chili'],[],[],[]),
  E('酸菜鱼',['cuisine_chuan','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_chili','allergen_fish'],[],[],[]),
  E('毛血旺',['cuisine_chuan','meal_lunch','meal_dinner','food_meat','food_seafood','dish_main','allergen_chili','allergen_soy'],[],[],[]),
  E('粉蒸肉',['cuisine_chuan','meal_lunch','meal_dinner','food_pork','dish_main','allergen_gluten'],[],[],[]),
  E('粉蒸排骨',['cuisine_chuan','meal_lunch','meal_dinner','food_pork','dish_main','allergen_gluten'],[],[],[]),
  E('粉蒸牛肉',['cuisine_chuan','meal_lunch','meal_dinner','food_beef','dish_main','allergen_gluten'],[],[],[]),
  E('冰粉',['cuisine_chuan','meal_afternoon_tea','food_dessert','dish_dessert'],[],[],[]),
  E('凉虾',['cuisine_chuan','meal_afternoon_tea','food_dessert','dish_dessert'],[],[],[]),
  E('凉糕',['cuisine_chuan','meal_afternoon_tea','food_dessert','dish_dessert'],[],[],[]),
  E('红糖糍粑',['cuisine_chuan','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten'],[],[],[]),
  E('糍粑',['cuisine_chuan','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten'],[],[],[]),
  E('叶儿粑',['cuisine_chuan','meal_breakfast','meal_afternoon_tea','food_rice','dish_snack','allergen_gluten'],[],[],[]),
  E('担担面',['cuisine_chuan','meal_breakfast','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_peanut','allergen_sesame'],[],[],[]),
  E('宜宾燃面',['cuisine_chuan','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_peanut'],[],[],[]),
  E('甜水面',['cuisine_chuan','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_sesame'],[],[],[]),
  E('川北凉粉',['cuisine_chuan','meal_lunch','meal_dinner','food_vegetarian','dish_snack','allergen_chili','allergen_soy'],[],[],[]),
  E('蹄花汤',['cuisine_chuan','meal_lunch','meal_dinner','food_pork','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('老妈蹄花',['cuisine_chuan','meal_lunch','meal_dinner','food_pork','food_soup','dish_soup','health_nourishing'],[],[],[]),

  // 粤菜经典
  E('白切鸡',['cuisine_yue','meal_lunch','meal_dinner','food_poultry','dish_main'],[],[],[]),
  E('豉油鸡',['cuisine_yue','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_soy'],[],[],[]),
  E('盐焗鸡',['cuisine_yue','meal_lunch','meal_dinner','food_poultry','dish_main'],[],[],[]),
  E('手撕鸡',['cuisine_yue','meal_lunch','meal_dinner','food_poultry','dish_appetizer','allergen_sesame','allergen_chili'],[],[],[]),
  E('干炒牛河',['cuisine_yue','meal_lunch','meal_dinner','food_noodles','food_beef','dish_staple','allergen_gluten','allergen_soy'],[],[],[]),
  E('滑蛋牛肉',['cuisine_yue','meal_lunch','meal_dinner','food_beef','dish_main','allergen_egg'],[],[],[]),
  E('滑蛋虾仁',['cuisine_yue','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_egg','allergen_shellfish'],[],[],[]),
  E('避风塘炒蟹',['cuisine_yue','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_shellfish','allergen_garlic'],[],[],[]),
  E('避风塘炒虾',['cuisine_yue','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_shellfish','allergen_garlic'],[],[],[]),
  E('猪脚姜',['cuisine_yue','meal_lunch','meal_dinner','food_pork','dish_soup','health_nourishing'],[],[],[]),
  E('双皮奶',['cuisine_yue','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy','allergen_egg'],[],[],[]),
  E('姜汁撞奶',['cuisine_yue','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy'],[],[],[]),
  E('白糖糕',['cuisine_yue','meal_breakfast','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten'],[],[],[]),
  E('马拉糕',['cuisine_yue','meal_breakfast','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_egg'],[],[],[]),
  E('黄金糕',['cuisine_yue','meal_breakfast','meal_afternoon_tea','food_dessert','dish_dessert','allergen_egg','allergen_gluten'],[],[],[]),
  E('红米肠',['cuisine_yue','meal_breakfast','meal_lunch','food_rice','dish_snack','allergen_shellfish','allergen_gluten'],[],[],[]),
  E('梅菜扣肉',['cuisine_yue','meal_lunch','meal_dinner','food_pork','dish_main','allergen_soy'],[],[],[]),
  E('咖喱鱼蛋',['cuisine_yue','meal_lunch','meal_afternoon_tea','food_seafood','dish_snack','allergen_chili'],[],[],[]),
  E('咖喱牛腩',['cuisine_yue','meal_lunch','meal_dinner','food_beef','dish_main','allergen_chili'],[],[],[]),
  E('咖喱鸡',['cuisine_yue','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_chili'],[],[],[]),
  E('煲仔饭',['cuisine_yue','meal_lunch','meal_dinner','food_rice','dish_staple','allergen_soy'],[],[],[]),
  E('腊味煲仔饭',['cuisine_yue','meal_lunch','meal_dinner','food_rice','dish_staple','allergen_soy'],[],[],[]),
  E('艇仔粥',['cuisine_yue','meal_breakfast','meal_lunch','food_congee','dish_staple','allergen_peanut','allergen_shellfish'],[],[],[]),
  E('及第粥',['cuisine_yue','meal_breakfast','meal_lunch','food_congee','dish_staple'],[],[],[]),
  E('皮蛋瘦肉粥',['cuisine_yue','meal_breakfast','meal_lunch','food_congee','dish_staple','allergen_egg'],[],[],[]),
  E('烧鹅',['cuisine_yue','meal_lunch','meal_dinner','food_poultry','dish_main'],[],[],[]),
  E('烧肉',['cuisine_yue','meal_lunch','meal_dinner','food_pork','dish_main'],[],[],[]),
  E('叉烧',['cuisine_yue','meal_lunch','meal_dinner','food_pork','dish_main','allergen_soy'],[],[],[]),
  E('蜜汁叉烧',['cuisine_yue','meal_lunch','meal_dinner','food_pork','dish_main','allergen_soy'],[],[],[]),
  E('炒花甲',['cuisine_yue','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_shellfish','allergen_chili'],[],[],[]),
  E('牛杂',['cuisine_yue','meal_lunch','meal_dinner','meal_midnight','food_beef','dish_snack','allergen_soy'],[],[],[]),
  E('萝卜牛杂',['cuisine_yue','meal_lunch','meal_dinner','meal_midnight','food_beef','dish_snack','allergen_soy'],[],[],[]),
  E('千层糕',['cuisine_yue','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_egg'],[],[],[]),
  E('椰汁糕',['cuisine_yue','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy'],[],[],[]),
  E('红豆糕',['cuisine_yue','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten'],[],[],[]),
  E('绿豆糕',['cuisine_yue','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten'],[],[],[]),
  E('马蹄糕',['cuisine_yue','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten'],[],[],[]),
  E('萝卜糕',['cuisine_yue','meal_breakfast','meal_afternoon_tea','food_vegetarian','dish_snack','allergen_gluten'],[],[],[]),
  E('芋头糕',['cuisine_yue','meal_breakfast','meal_afternoon_tea','food_vegetarian','dish_snack','allergen_gluten'],[],[],[]),
  E('潮州蚝烙',['cuisine_yue','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_shellfish','allergen_egg','allergen_gluten'],[],[],[]),
  E('潮州牛肉丸',['cuisine_yue','meal_lunch','meal_dinner','food_beef','dish_snack'],[],[],[]),
  E('客家酿豆腐',['cuisine_yue','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_soy'],[],[],[]),
  E('顺德鱼生',['cuisine_yue','meal_lunch','meal_dinner','food_seafood','dish_appetizer','allergen_fish'],[],[],[]),

  // 湘菜经典
  E('剁椒鱼头',['cuisine_xiang','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_fish','allergen_chili'],[],[],[]),
  E('辣椒炒肉',['cuisine_xiang','meal_lunch','meal_dinner','food_pork','dish_main','allergen_chili','allergen_soy'],[],[],[]),
  E('小炒黄牛肉',['cuisine_xiang','meal_lunch','meal_dinner','food_beef','dish_main','allergen_chili','allergen_soy'],[],[],[]),
  E('小炒肉',['cuisine_xiang','meal_lunch','meal_dinner','food_pork','dish_main','allergen_chili','allergen_soy'],[],[],[]),

  // 日式经典
  E('日式咖喱饭',['cuisine_japanese','meal_lunch','meal_dinner','food_rice','dish_staple','allergen_chili'],[],[],[]),
  E('日式亲子丼',['cuisine_japanese','meal_lunch','meal_dinner','food_rice','food_poultry','dish_staple','allergen_egg','allergen_soy'],[],[],[]),
  E('日式牛丼',['cuisine_japanese','meal_lunch','meal_dinner','food_rice','food_beef','dish_staple','allergen_soy'],[],[],[]),
  E('日式天丼',['cuisine_japanese','meal_lunch','meal_dinner','food_rice','food_seafood','dish_staple','allergen_gluten','allergen_shellfish','allergen_egg'],[],[],[]),
  E('日式炸猪排',['cuisine_japanese','meal_lunch','meal_dinner','food_pork','dish_main','allergen_gluten','allergen_egg'],[],[],[]),
  E('日式照烧鸡',['cuisine_japanese','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_soy'],[],[],[]),
  E('日式关东煮',['cuisine_japanese','meal_lunch','meal_dinner','meal_midnight','food_meat','food_seafood','dish_snack','allergen_soy','allergen_fish'],[],[],[]),
  E('日式大阪烧',['cuisine_japanese','meal_lunch','meal_dinner','food_pancake','dish_main','allergen_gluten','allergen_egg','allergen_shellfish'],[],[],[]),
  E('日式章鱼烧',['cuisine_japanese','meal_afternoon_tea','meal_midnight','food_seafood','dish_snack','allergen_gluten','allergen_shellfish','allergen_egg'],[],[],[]),
  E('日式饭团',['cuisine_japanese','meal_breakfast','meal_lunch','food_rice','dish_staple','allergen_soy'],[],[],[]),
  E('日式手卷',['cuisine_japanese','meal_lunch','meal_dinner','food_rice','food_seafood','dish_appetizer','allergen_fish','allergen_soy'],[],[],[]),
  E('日式抹茶',['cuisine_japanese','meal_afternoon_tea','food_tea','dish_beverage'],[],[],[]),
  E('日式团子',['cuisine_japanese','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten'],[],[],[]),
  E('日式大福',['cuisine_japanese','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten'],[],[],[]),
  E('日式铜锣烧',['cuisine_japanese','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_egg','allergen_dairy'],[],[],[]),
  E('日式鲷鱼烧',['cuisine_japanese','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_egg','allergen_dairy'],[],[],[]),
  E('日式刨冰',['cuisine_japanese','meal_afternoon_tea','food_dessert','dish_dessert'],[],[],[]),
  E('日式布丁',['cuisine_japanese','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy','allergen_egg'],[],[],[]),
  E('日式寿喜锅',['cuisine_japanese','meal_lunch','meal_dinner','food_beef','food_hotpot','dish_main','allergen_soy','allergen_egg'],[],[],[]),

  // 韩式经典
  E('韩式炸鸡',['cuisine_korean','meal_lunch','meal_dinner','meal_midnight','food_poultry','dish_main','allergen_gluten','allergen_chili'],[],[],[]),
  E('韩式参鸡汤',['cuisine_korean','meal_lunch','meal_dinner','food_poultry','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('韩式部队锅',['cuisine_korean','meal_lunch','meal_dinner','food_meat','food_hotpot','dish_main','allergen_chili','allergen_soy','allergen_gluten'],[],[],[]),
  E('韩式杂菜',['cuisine_korean','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_soy','allergen_sesame'],[],[],[]),
  E('韩式紫菜包饭',['cuisine_korean','meal_breakfast','meal_lunch','food_rice','dish_staple','allergen_soy'],[],[],[]),
  E('韩式辣炒年糕',['cuisine_korean','meal_lunch','meal_afternoon_tea','food_rice','dish_snack','allergen_chili','allergen_soy'],[],[],[]),
  E('韩式炸酱面',['cuisine_korean','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_soy'],[],[],[]),
  E('韩式冷面',['cuisine_korean','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_soy','allergen_egg'],[],[],[]),
  E('韩式烤牛肉',['cuisine_korean','meal_lunch','meal_dinner','food_beef','dish_main','allergen_soy','allergen_garlic'],[],[],[]),

  // 泰式经典
  E('泰式冬阴功',['cuisine_thai','meal_lunch','meal_dinner','food_soup','food_seafood','dish_soup','allergen_chili','allergen_shellfish'],[],[],[]),
  E('泰式绿咖喱',['cuisine_thai','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_chili','allergen_dairy'],[],[],[]),
  E('泰式炒河粉',['cuisine_thai','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_shellfish','allergen_peanut'],[],[],[]),
  E('泰式芒果糯米饭',['cuisine_thai','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy'],[],[],[]),
  E('泰式青木瓜沙拉',['cuisine_thai','meal_lunch','meal_dinner','food_vegetarian','dish_salad','allergen_chili','allergen_peanut','allergen_shellfish'],[],[],[]),

  // 越南经典
  E('越南河粉',['cuisine_vietnamese','meal_breakfast','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten'],[],[],[]),
  E('越南春卷',['cuisine_vietnamese','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_gluten','allergen_shellfish'],[],[],[]),

  // 新加坡经典
  E('新加坡海南鸡饭',['cuisine_other','meal_lunch','meal_dinner','food_rice','food_poultry','dish_staple','allergen_soy'],[],[],[]),
  E('新加坡肉骨茶',['cuisine_other','meal_breakfast','meal_lunch','meal_dinner','food_pork','food_soup','dish_soup','health_nourishing','allergen_soy'],[],[],[]),
  E('新加坡叻沙',['cuisine_other','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_shellfish','allergen_dairy'],[],[],[]),

  // 印度经典
  E('印度烤鸡',['cuisine_indian','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_chili','allergen_dairy'],[],[],[]),
  E('印度奶油鸡',['cuisine_indian','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_chili','allergen_dairy'],[],[],[]),
  E('印度馕',['cuisine_indian','meal_lunch','meal_dinner','food_pancake','dish_staple','allergen_gluten','allergen_dairy'],[],[],[]),

  // 意式经典
  E('意式千层面',['cuisine_italian','meal_lunch','meal_dinner','food_gluten','dish_main','allergen_gluten','allergen_dairy','allergen_egg'],[],[],[]),
  E('意式烩饭',['cuisine_italian','meal_lunch','meal_dinner','food_rice','dish_staple','allergen_dairy'],[],[],[]),
  E('意式提拉米苏',['cuisine_italian','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy','allergen_egg','allergen_gluten'],[],[],[]),
  E('意式奶冻',['cuisine_italian','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy'],[],[],[]),
  E('意式冰淇淋',['cuisine_italian','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy'],[],[],[]),

  // 法式经典
  E('法式马卡龙',['cuisine_french','meal_afternoon_tea','food_dessert','dish_dessert','allergen_egg','allergen_tree_nut'],[],[],[]),
  E('法式可颂',['cuisine_french','meal_breakfast','meal_afternoon_tea','food_bun','dish_snack','allergen_gluten','allergen_dairy','allergen_egg'],[],[],[]),
  E('法式焦糖布丁',['cuisine_french','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy','allergen_egg'],[],[],[]),

  // 西班牙经典
  E('西班牙海鲜饭',['cuisine_spanish','meal_lunch','meal_dinner','food_rice','food_seafood','dish_staple','allergen_shellfish','allergen_fish'],[],[],[]),
  E('西班牙油条',['cuisine_spanish','meal_breakfast','meal_afternoon_tea','food_snack','dish_snack','allergen_gluten'],[],[],[]),

  // 德国经典
  E('德国香肠',['cuisine_german','meal_lunch','meal_dinner','food_meat','dish_main'],[],[],[]),
  E('德国酸菜',['cuisine_german','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer'],[],[],[]),
  E('德国啤酒',['cuisine_german','meal_dinner','meal_midnight','food_alcohol','dish_beverage','allergen_gluten'],[],[],[]),

  // 英式经典
  E('英式炸鱼薯条',['cuisine_british','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_gluten','allergen_fish'],[],[],[]),
  E('英式早餐',['cuisine_british','meal_breakfast','food_meat','food_egg','dish_breakfast','allergen_egg','allergen_gluten'],[],[],[]),
  E('英式下午茶',['cuisine_british','meal_afternoon_tea','food_tea','food_dessert','dish_beverage','allergen_gluten','allergen_dairy'],[],[],[]),
  E('英式司康',['cuisine_british','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_dairy','allergen_egg'],[],[],[]),

  // 美式经典
  E('美式汉堡',['cuisine_american','meal_lunch','meal_dinner','food_beef','dish_main','allergen_gluten','allergen_dairy'],[],[],[]),
  E('美式热狗',['cuisine_american','meal_lunch','meal_dinner','food_meat','dish_main','allergen_gluten'],[],[],[]),
  E('美式炸鸡',['cuisine_american','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_gluten'],[],[],[]),
  E('美式苹果派',['cuisine_american','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_dairy','allergen_egg'],[],[],[]),
  E('美式芝士蛋糕',['cuisine_american','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy','allergen_gluten','allergen_egg'],[],[],[]),
  E('美式布朗尼',['cuisine_american','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_egg','allergen_dairy','allergen_tree_nut'],[],[],[]),
  E('美式松饼',['cuisine_american','meal_breakfast','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_egg','allergen_dairy'],[],[],[]),
  E('美式薯条',['cuisine_american','meal_lunch','meal_afternoon_tea','food_snack','dish_snack'],[],[],[]),
  E('美式洋葱圈',['cuisine_american','meal_lunch','meal_afternoon_tea','food_snack','dish_snack','allergen_gluten'],[],[],[]),
  E('美式烧烤',['cuisine_american','meal_lunch','meal_dinner','food_meat','food_bbq','dish_main'],[],[],[]),

  // 墨西哥
  E('墨西哥玉米饼',['cuisine_mexican','meal_lunch','meal_dinner','food_pancake','dish_staple','allergen_gluten'],[],[],[]),
  E('墨西哥玉米片',['cuisine_mexican','meal_afternoon_tea','food_snack','dish_snack','allergen_gluten','allergen_chili'],[],[],[]),

  // 土耳其
  E('土耳其烤肉',['cuisine_middle_eastern','meal_lunch','meal_dinner','food_meat','dish_main','allergen_gluten'],[],[],[]),

  // 希腊
  E('希腊沙拉',['cuisine_greek','meal_lunch','meal_dinner','food_vegetarian','dish_salad','allergen_dairy'],[],[],[]),

  // 家常菜
  E('红烧肉',['cuisine_other','meal_lunch','meal_dinner','food_pork','dish_main','allergen_soy'],[],[],[]),
  E('红烧排骨',['cuisine_other','meal_lunch','meal_dinner','food_pork','dish_main','allergen_soy'],[],[],[]),
  E('红烧鸡块',['cuisine_other','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_soy'],[],[],[]),
  E('红烧鱼块',['cuisine_other','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_soy','allergen_fish'],[],[],[]),
  E('红烧牛肉',['cuisine_other','meal_lunch','meal_dinner','food_beef','dish_main','allergen_soy'],[],[],[]),
  E('红烧羊肉',['cuisine_other','meal_lunch','meal_dinner','food_lamb','dish_main','allergen_soy'],[],[],[]),
  E('红烧猪蹄',['cuisine_other','meal_lunch','meal_dinner','food_pork','dish_main','allergen_soy','health_nourishing'],[],[],[]),
  E('红烧牛腩',['cuisine_other','meal_lunch','meal_dinner','food_beef','dish_main','allergen_soy'],[],[],[]),
  E('糖醋排骨',['cuisine_other','meal_lunch','meal_dinner','food_pork','dish_main','allergen_soy'],[],[],[]),
  E('糖醋鱼',['cuisine_other','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_gluten','allergen_fish'],[],[],[]),
  E('糖醋里脊',['cuisine_other','meal_lunch','meal_dinner','food_pork','dish_main','allergen_gluten'],[],[],[]),
  E('清蒸鱼',['cuisine_other','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_fish','allergen_soy'],[],[],[]),
  E('清蒸鲈鱼',['cuisine_other','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_fish','allergen_soy'],[],[],[]),
  E('酸辣土豆丝',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_chili'],[],[],[]),
  E('酸辣白菜',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_chili'],[],[],[]),
  E('酸辣粉',['cuisine_other','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_peanut'],[],[],[]),
  E('酸辣汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','allergen_chili','allergen_egg','allergen_gluten'],[],[],[]),
  E('鱼香肉丝',['cuisine_chuan','meal_lunch','meal_dinner','food_pork','dish_main','allergen_chili','allergen_soy'],[],[],[]),
  E('回锅肉',['cuisine_chuan','meal_lunch','meal_dinner','food_pork','dish_main','allergen_chili','allergen_soy'],[],[],[]),
  E('干煸豆角',['cuisine_chuan','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_chili','allergen_soy'],[],[],[]),
  E('干煸四季豆',['cuisine_chuan','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_chili','allergen_soy'],[],[],[]),
  E('水煮鱼',['cuisine_chuan','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_chili','allergen_fish'],[],[],[]),
  E('锅包肉',['cuisine_dongbei','meal_lunch','meal_dinner','food_pork','dish_main','allergen_gluten'],[],[],[]),
  E('溜肉段',['cuisine_dongbei','meal_lunch','meal_dinner','food_pork','dish_main','allergen_gluten','allergen_soy'],[],[],[]),
  E('地三鲜',['cuisine_dongbei','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_soy'],[],[],[]),
  E('番茄炒蛋',['cuisine_other','meal_lunch','meal_dinner','food_egg','dish_main','allergen_egg'],[],[],[]),
  E('蒸鸡蛋羹',['cuisine_other','meal_breakfast','meal_lunch','meal_dinner','food_egg','dish_main','allergen_egg'],[],[],[]),
  E('炒鸡蛋',['cuisine_other','meal_breakfast','meal_lunch','meal_dinner','food_egg','dish_main','allergen_egg'],[],[],[]),
  E('红烧豆腐',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_soy'],[],[],[]),
  E('家常豆腐',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_soy','allergen_chili'],[],[],[]),
  E('红烧茄子',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_soy'],[],[],[]),
  E('鱼香茄子',['cuisine_chuan','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_chili','allergen_soy'],[],[],[]),
  E('蒜蓉茄子',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_garlic'],[],[],[]),
  E('凉拌茄子',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_garlic','allergen_sesame'],[],[],[]),
  E('炒豆芽',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒空心菜',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒菜心',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒油麦菜',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒生菜',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒菠菜',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒大白菜',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒花菜',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒西兰花',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒藕片',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒土豆丝',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒茄子',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒冬瓜',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒南瓜',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒丝瓜',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒苦瓜',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒黄瓜',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒西葫芦',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('炒山药',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('韭菜炒蛋',['cuisine_other','meal_lunch','meal_dinner','food_egg','dish_main','allergen_egg'],[],[],[]),
  E('洋葱炒蛋',['cuisine_other','meal_lunch','meal_dinner','food_egg','dish_main','allergen_egg'],[],[],[]),
  E('苦瓜炒蛋',['cuisine_other','meal_lunch','meal_dinner','food_egg','dish_main','allergen_egg'],[],[],[]),
  E('虾仁炒蛋',['cuisine_other','meal_lunch','meal_dinner','food_egg','food_seafood','dish_main','allergen_egg','allergen_shellfish'],[],[],[]),
  E('青椒炒蛋',['cuisine_other','meal_lunch','meal_dinner','food_egg','dish_main','allergen_egg'],[],[],[]),
  E('肉末豆腐',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_soy'],[],[],[]),
  E('虾仁豆腐',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','food_seafood','dish_main','allergen_soy','allergen_shellfish'],[],[],[]),
  E('皮蛋豆腐',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_soy','allergen_egg'],[],[],[]),
  E('凉拌豆腐',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_soy'],[],[],[]),
  E('小葱拌豆腐',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_soy'],[],[],[]),
  E('蒸茄子',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_main'],[],[],[]),
  E('烤茄子',['cuisine_other','meal_lunch','meal_dinner','meal_midnight','food_vegetarian','dish_snack','allergen_garlic','allergen_chili'],[],[],[]),

  // 炖菜
  E('排骨炖豆角',['cuisine_dongbei','meal_lunch','meal_dinner','food_pork','food_stew','dish_main','allergen_soy'],[],[],[]),
  E('排骨炖冬瓜',['cuisine_other','meal_lunch','meal_dinner','food_pork','food_stew','dish_soup'],[],[],[]),
  E('排骨炖莲藕',['cuisine_other','meal_lunch','meal_dinner','food_pork','food_stew','dish_soup','health_nourishing'],[],[],[]),
  E('排骨炖玉米',['cuisine_other','meal_lunch','meal_dinner','food_pork','food_stew','dish_soup'],[],[],[]),
  E('排骨炖土豆',['cuisine_dongbei','meal_lunch','meal_dinner','food_pork','food_stew','dish_main','allergen_soy'],[],[],[]),
  E('排骨炖海带',['cuisine_other','meal_lunch','meal_dinner','food_pork','food_stew','dish_soup'],[],[],[]),
  E('排骨炖山药',['cuisine_other','meal_lunch','meal_dinner','food_pork','food_stew','dish_soup','health_nourishing'],[],[],[]),
  E('排骨炖萝卜',['cuisine_other','meal_lunch','meal_dinner','food_pork','food_stew','dish_soup'],[],[],[]),
  E('牛肉炖萝卜',['cuisine_other','meal_lunch','meal_dinner','food_beef','food_stew','dish_main','allergen_soy'],[],[],[]),
  E('牛肉炖土豆',['cuisine_other','meal_lunch','meal_dinner','food_beef','food_stew','dish_main','allergen_soy'],[],[],[]),
  E('牛肉炖番茄',['cuisine_other','meal_lunch','meal_dinner','food_beef','food_stew','dish_main'],[],[],[]),
  E('牛肉炖胡萝卜',['cuisine_other','meal_lunch','meal_dinner','food_beef','food_stew','dish_main'],[],[],[]),
  E('番茄炖牛腩',['cuisine_other','meal_lunch','meal_dinner','food_beef','food_stew','dish_main'],[],[],[]),
  E('酸菜炖粉条',['cuisine_dongbei','meal_lunch','meal_dinner','food_pork','food_stew','dish_main','allergen_soy'],[],[],[]),
  E('酸菜炖排骨',['cuisine_dongbei','meal_lunch','meal_dinner','food_pork','food_stew','dish_main','allergen_soy'],[],[],[]),
  E('酸菜炖大骨',['cuisine_dongbei','meal_lunch','meal_dinner','food_pork','food_stew','dish_main','allergen_soy'],[],[],[]),
  E('酸菜炖血肠',['cuisine_dongbei','meal_lunch','meal_dinner','food_pork','food_stew','dish_main','allergen_soy'],[],[],[]),
  E('豆腐炖鱼',['cuisine_other','meal_lunch','meal_dinner','food_seafood','food_stew','dish_main','allergen_soy','allergen_fish'],[],[],[]),
  E('鱼头炖豆腐',['cuisine_other','meal_lunch','meal_dinner','food_seafood','food_stew','dish_soup','allergen_fish','allergen_soy','health_nourishing'],[],[],[]),
  E('炖牛肉',['cuisine_other','meal_lunch','meal_dinner','food_beef','food_stew','dish_main','allergen_soy'],[],[],[]),
  E('炖羊肉',['cuisine_other','meal_lunch','meal_dinner','food_lamb','food_stew','dish_main','health_nourishing'],[],[],[]),
  E('炖鸡',['cuisine_other','meal_lunch','meal_dinner','food_poultry','food_stew','dish_main','health_nourishing'],[],[],[]),
  E('炖鸭',['cuisine_other','meal_lunch','meal_dinner','food_poultry','food_stew','dish_main','health_nourishing'],[],[],[]),
  E('鸡肉炖蘑菇',['cuisine_dongbei','meal_lunch','meal_dinner','food_poultry','food_stew','dish_main','allergen_soy'],[],[],[]),
  E('鸡肉炖土豆',['cuisine_dongbei','meal_lunch','meal_dinner','food_poultry','food_stew','dish_main','allergen_soy'],[],[],[]),
  E('鸡肉炖粉条',['cuisine_dongbei','meal_lunch','meal_dinner','food_poultry','food_stew','dish_main','allergen_soy'],[],[],[]),
  E('鸭肉炖冬瓜',['cuisine_other','meal_lunch','meal_dinner','food_poultry','food_stew','dish_soup','health_nourishing'],[],[],[]),

  // 汤品
  E('紫菜蛋花汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','allergen_egg'],[],[],[]),
  E('番茄蛋花汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','allergen_egg'],[],[],[]),
  E('冬瓜汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup'],[],[],[]),
  E('萝卜汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup'],[],[],[]),
  E('海带汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup'],[],[],[]),
  E('豆腐汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','allergen_soy'],[],[],[]),
  E('菌菇汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup'],[],[],[]),
  E('排骨汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('大骨汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('乌鸡汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('老鸭汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('鲫鱼汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','allergen_fish','health_nourishing'],[],[],[]),
  E('冬瓜排骨汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('萝卜排骨汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('莲藕排骨汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('海带排骨汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('玉米排骨汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('山药排骨汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('冬瓜老鸭汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('酸萝卜老鸭汤',['cuisine_chuan','meal_lunch','meal_dinner','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('红枣鸡汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('枸杞鸡汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('当归鸡汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('豆腐鱼头汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','allergen_fish','allergen_soy','health_nourishing'],[],[],[]),
  E('鱼头豆腐汤',['cuisine_other','meal_lunch','meal_dinner','food_soup','dish_soup','allergen_fish','allergen_soy','health_nourishing'],[],[],[]),
  E('胡辣汤',['cuisine_yu','meal_breakfast','food_soup','dish_soup','allergen_chili','allergen_gluten','allergen_soy'],[],[],[]),

  // 凉菜
  E('凉拌黄瓜',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_garlic'],[],[],[]),
  E('凉拌木耳',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_garlic','allergen_chili'],[],[],[]),
  E('凉拌海带',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_garlic','allergen_chili'],[],[],[]),
  E('凉拌腐竹',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_soy','allergen_chili'],[],[],[]),
  E('凉拌豆皮',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_soy','allergen_chili'],[],[],[]),
  E('凉拌土豆丝',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_chili'],[],[],[]),
  E('凉拌藕片',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_chili'],[],[],[]),
  E('凉拌三丝',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_chili','allergen_soy'],[],[],[]),
  E('凉拌鸡丝',['cuisine_other','meal_lunch','meal_dinner','food_poultry','dish_appetizer','allergen_chili','allergen_sesame'],[],[],[]),
  E('凉拌牛肉',['cuisine_other','meal_lunch','meal_dinner','food_beef','dish_appetizer','allergen_chili','allergen_sesame'],[],[],[]),
  E('凉拌猪耳',['cuisine_other','meal_lunch','meal_dinner','food_pork','dish_appetizer','allergen_chili','allergen_sesame'],[],[],[]),
  E('凉拌皮蛋',['cuisine_other','meal_lunch','meal_dinner','food_egg','dish_appetizer','allergen_egg','allergen_garlic'],[],[],[]),
  E('凉拌海蜇',['cuisine_other','meal_lunch','meal_dinner','food_seafood','dish_appetizer','allergen_sesame','allergen_chili'],[],[],[]),
  E('蒜泥白肉',['cuisine_chuan','meal_lunch','meal_dinner','food_pork','dish_appetizer','allergen_chili','allergen_garlic','allergen_soy'],[],[],[]),
  E('蒜泥黄瓜',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_garlic'],[],[],[]),
  E('蒜泥茄子',['cuisine_other','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_garlic'],[],[],[]),
  E('红油耳丝',['cuisine_chuan','meal_lunch','meal_dinner','food_pork','dish_appetizer','allergen_chili','allergen_sesame'],[],[],[]),
  E('泡椒凤爪',['cuisine_chuan','meal_lunch','meal_dinner','meal_midnight','food_poultry','dish_snack','allergen_chili'],[],[],[]),
  E('酱牛肉',['cuisine_other','meal_lunch','meal_dinner','food_beef','dish_appetizer','allergen_soy','health_high_protein'],[],[],[]),
  E('酱肘子',['cuisine_other','meal_lunch','meal_dinner','food_pork','dish_appetizer','allergen_soy'],[],[],[]),

  // 主食/面食
  E('煎饼',['cuisine_other','meal_breakfast','food_pancake','dish_staple','allergen_gluten'],[],[],[]),
  E('煎饼果子',['cuisine_other','meal_breakfast','food_pancake','dish_staple','allergen_gluten','allergen_egg'],[],[],['煎饼馃子']),
  E('杂粮煎饼',['cuisine_other','meal_breakfast','food_pancake','dish_staple','allergen_gluten'],[],[],[]),
  E('鸡蛋灌饼',['cuisine_other','meal_breakfast','food_pancake','dish_staple','allergen_gluten','allergen_egg'],[],[],[]),
  E('手抓饼',['cuisine_other','meal_breakfast','meal_lunch','food_pancake','dish_staple','allergen_gluten'],[],[],[]),
  E('葱油饼',['cuisine_other','meal_breakfast','meal_lunch','food_pancake','dish_staple','allergen_gluten'],[],[],[]),
  E('酱香饼',['cuisine_other','meal_breakfast','meal_lunch','food_pancake','dish_staple','allergen_gluten','allergen_chili','allergen_soy'],[],[],[]),
  E('千层饼',['cuisine_other','meal_breakfast','meal_lunch','food_pancake','dish_staple','allergen_gluten'],[],[],[]),
  E('肉夹馍',['cuisine_northwest','meal_breakfast','meal_lunch','meal_dinner','food_pancake','food_meat','dish_staple','allergen_gluten'],[],[],[]),
  E('凉皮',['cuisine_northwest','meal_breakfast','meal_lunch','meal_dinner','food_gluten','dish_staple','allergen_gluten','allergen_chili','allergen_sesame'],[],[],[]),
  E('凉面',['cuisine_other','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_sesame'],[],[],[]),
  E('热干面',['cuisine_e','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten','allergen_sesame','allergen_soy'],[],[],[]),
  E('炸酱面',['cuisine_beijing','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_soy'],[],[],[]),
  E('油泼面',['cuisine_northwest','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili'],[],[],[]),
  E('biangbiang面',['cuisine_northwest','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_soy'],[],[],[]),
  E('臊子面',['cuisine_northwest','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_soy'],[],[],[]),
  E('刀削面',['cuisine_jin','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten'],[],[],[]),
  E('拉面',['cuisine_northwest','meal_breakfast','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten'],[],[],[]),
  E('炒面',['cuisine_other','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_soy'],[],[],[]),
  E('炒饭',['cuisine_other','meal_lunch','meal_dinner','food_rice','dish_staple','allergen_soy'],[],[],[]),
  E('蛋炒饭',['cuisine_other','meal_lunch','meal_dinner','food_rice','dish_staple','allergen_egg','allergen_soy'],[],[],[]),
  E('扬州炒饭',['cuisine_su','meal_lunch','meal_dinner','food_rice','dish_staple','allergen_egg','allergen_shellfish','allergen_soy'],[],[],[]),
  E('蛋包饭',['cuisine_other','meal_lunch','meal_dinner','food_rice','dish_staple','allergen_egg','allergen_soy'],[],[],[]),
  E('石锅拌饭',['cuisine_korean','meal_lunch','meal_dinner','food_rice','dish_staple','allergen_egg','allergen_soy','allergen_chili'],[],[],[]),
  E('粽子',['cuisine_other','meal_breakfast','meal_afternoon_tea','food_rice','dish_dessert','allergen_gluten'],[],[],[]),
  E('月饼',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_egg'],[],[],[]),
  E('汤圆',['cuisine_other','meal_breakfast','meal_afternoon_tea','food_rice','dish_dessert','allergen_gluten'],[],[],[]),
  E('元宵',['cuisine_other','meal_breakfast','meal_afternoon_tea','food_rice','dish_dessert','allergen_gluten'],[],[],[]),
  E('年糕',['cuisine_other','meal_breakfast','meal_afternoon_tea','food_rice','dish_dessert','allergen_gluten'],[],[],[]),
  E('青团',['cuisine_other','meal_breakfast','meal_afternoon_tea','food_rice','dish_dessert','allergen_gluten'],[],[],[]),
  E('桂花糕',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten'],[],[],[]),
  E('发糕',['cuisine_other','meal_breakfast','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten'],[],[],[]),
  E('驴打滚',['cuisine_beijing','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_soy'],[],[],[]),
  E('豌豆黄',['cuisine_beijing','meal_afternoon_tea','food_dessert','dish_dessert'],[],[],[]),
  E('麻花',['cuisine_other','meal_breakfast','meal_afternoon_tea','food_snack','dish_snack','allergen_gluten'],[],[],[]),
  E('油条',['cuisine_other','meal_breakfast','food_pancake','dish_staple','allergen_gluten'],[],[],[]),
  E('麻团',['cuisine_other','meal_breakfast','meal_afternoon_tea','food_rice','dish_snack','allergen_gluten','allergen_sesame'],[],[],[]),
  E('炸糕',['cuisine_other','meal_breakfast','meal_afternoon_tea','food_rice','dish_snack','allergen_gluten'],[],[],[]),
  E('春卷',['cuisine_other','meal_breakfast','meal_lunch','food_vegetarian','dish_snack','allergen_gluten'],[],[],[]),
  E('炸鸡腿',['cuisine_other','meal_lunch','meal_dinner','food_poultry','dish_snack','allergen_gluten'],[],[],[]),
  E('炸鸡翅',['cuisine_other','meal_lunch','meal_dinner','food_poultry','dish_snack','allergen_gluten'],[],[],[]),
  E('炸鸡排',['cuisine_other','meal_lunch','meal_dinner','food_poultry','dish_snack','allergen_gluten'],[],[],[]),
  E('烤肉',['cuisine_other','meal_lunch','meal_dinner','meal_midnight','food_meat','food_bbq','dish_main'],[],[],[]),
  E('烤鸡',['cuisine_other','meal_lunch','meal_dinner','food_poultry','dish_main'],[],[],[]),
  E('烤鸭',['cuisine_other','meal_lunch','meal_dinner','food_poultry','dish_main'],[],[],[]),
  E('烤鱼',['cuisine_other','meal_lunch','meal_dinner','meal_midnight','food_seafood','dish_main','allergen_fish','allergen_chili'],[],[],[]),
  E('烤羊排',['cuisine_other','meal_lunch','meal_dinner','meal_midnight','food_lamb','food_bbq','dish_main','allergen_chili'],[],[],[]),
  E('烤串',['cuisine_other','meal_lunch','meal_dinner','meal_midnight','food_meat','food_bbq','dish_snack','allergen_chili'],[],[],[]),
  E('麻辣烫',['cuisine_other','meal_lunch','meal_dinner','meal_midnight','food_meat','food_vegetarian','dish_snack','allergen_chili','allergen_soy'],[],[],[]),
  E('冒菜',['cuisine_chuan','meal_lunch','meal_dinner','meal_midnight','food_meat','food_vegetarian','dish_main','allergen_chili','allergen_soy'],[],[],[]),
  E('火锅',['cuisine_other','meal_lunch','meal_dinner','food_meat','food_hotpot','dish_main','allergen_chili','allergen_soy'],[],[],[]),
  E('串串香',['cuisine_chuan','meal_lunch','meal_dinner','meal_midnight','food_meat','dish_snack','allergen_chili','allergen_soy'],[],[],[]),
  E('钵钵鸡',['cuisine_chuan','meal_lunch','meal_dinner','meal_midnight','food_poultry','dish_snack','allergen_chili','allergen_sesame'],[],[],[]),
  E('关东煮',['cuisine_japanese','meal_lunch','meal_dinner','meal_midnight','food_meat','dish_snack','allergen_soy'],[],[],[]),

  // 甜品
  E('蛋糕',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_egg','allergen_dairy'],[],[],[]),
  E('芝士蛋糕',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy','allergen_gluten','allergen_egg'],[],[],[]),
  E('慕斯蛋糕',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy','allergen_egg'],[],[],[]),
  E('千层蛋糕',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy','allergen_egg','allergen_gluten'],[],[],[]),
  E('布丁',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy','allergen_egg'],[],[],[]),
  E('焦糖布丁',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy','allergen_egg'],[],[],[]),
  E('果冻',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert'],[],[],[]),
  E('烧仙草',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert'],[],[],[]),
  E('芋圆',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert'],[],[],[]),
  E('西米露',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy'],[],[],[]),
  E('杨枝甘露',['cuisine_yue','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy'],[],[],[]),
  E('红豆沙',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert'],[],[],[]),
  E('绿豆沙',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert'],[],[],[]),
  E('芝麻糊',['cuisine_other','meal_breakfast','meal_afternoon_tea','food_dessert','dish_dessert','allergen_sesame'],[],[],[]),
  E('花生糊',['cuisine_other','meal_breakfast','meal_afternoon_tea','food_dessert','dish_dessert','allergen_peanut'],[],[],[]),
  E('糯米糍',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_dairy'],[],[],[]),
  E('雪糕',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy'],[],[],[]),
  E('冰棍',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert'],[],[],[]),
  E('冰淇淋',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy'],[],[],[]),
  E('刨冰',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert'],[],[],[]),
  E('龟苓膏',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert'],[],[],[]),

  // 面点
  E('红糖馒头',['cuisine_other','meal_breakfast','food_bun','dish_staple','allergen_gluten'],[],[],[]),
  E('花卷',['cuisine_other','meal_breakfast','food_bun','dish_staple','allergen_gluten'],[],[],[]),
  E('葱油花卷',['cuisine_other','meal_breakfast','food_bun','dish_staple','allergen_gluten'],[],[],[]),
  E('豆沙包',['cuisine_other','meal_breakfast','food_bun','dish_staple','allergen_gluten'],[],[],[]),
  E('奶黄包',['cuisine_other','meal_breakfast','food_bun','dish_staple','allergen_gluten','allergen_dairy','allergen_egg'],[],[],[]),
  E('莲蓉包',['cuisine_other','meal_breakfast','food_bun','dish_staple','allergen_gluten'],[],[],[]),
  E('叉烧包',['cuisine_yue','meal_breakfast','meal_lunch','food_bun','dish_staple','allergen_gluten','allergen_soy'],[],[],[]),
  E('流沙包',['cuisine_yue','meal_breakfast','meal_lunch','food_bun','dish_staple','allergen_gluten','allergen_dairy','allergen_egg'],[],[],[]),
  E('烧卖',['cuisine_other','meal_breakfast','meal_lunch','food_dumpling','dish_staple','allergen_gluten'],[],[],[]),
  E('蒸饺',['cuisine_other','meal_breakfast','meal_lunch','meal_dinner','food_dumpling','dish_staple','allergen_gluten'],[],[],[]),
  E('水饺',['cuisine_other','meal_breakfast','meal_lunch','meal_dinner','food_dumpling','dish_staple','allergen_gluten'],[],[],[]),
  E('锅贴',['cuisine_other','meal_breakfast','meal_lunch','meal_dinner','food_dumpling','dish_staple','allergen_gluten'],[],[],[]),
  E('煎饺',['cuisine_other','meal_breakfast','meal_lunch','meal_dinner','food_dumpling','dish_staple','allergen_gluten'],[],[],[]),
  E('韭菜盒子',['cuisine_dongbei','meal_breakfast','meal_lunch','food_dumpling','dish_snack','allergen_gluten','allergen_egg'],[],[],[]),
  E('蛋挞',['cuisine_yue','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_egg','allergen_dairy'],[],[],[]),
  E('葡式蛋挞',['cuisine_portuguese','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_egg','allergen_dairy'],[],[],[]),
  E('面包',['cuisine_other','meal_breakfast','meal_afternoon_tea','food_bun','dish_staple','allergen_gluten'],[],[],[]),
  E('吐司',['cuisine_other','meal_breakfast','meal_afternoon_tea','food_bun','dish_staple','allergen_gluten'],[],[],[]),
  E('法棍',['cuisine_french','meal_breakfast','meal_lunch','food_bun','dish_staple','allergen_gluten'],[],[],[]),

  // 饮品
  E('抹茶',['cuisine_japanese','meal_afternoon_tea','food_tea','dish_beverage'],[],[],[]),
  E('热巧克力',['cuisine_other','meal_afternoon_tea','food_cocoa','dish_beverage','allergen_dairy'],[],[],[]),
  E('冰美式',['cuisine_other','meal_afternoon_tea','food_coffee','dish_beverage'],[],[],[]),
  E('冰拿铁',['cuisine_other','meal_afternoon_tea','food_coffee','dish_beverage','allergen_dairy'],[],[],[]),
  E('冰摩卡',['cuisine_other','meal_afternoon_tea','food_coffee','dish_beverage','allergen_dairy'],[],[],[]),
  E('芒果奶昔',['cuisine_other','meal_afternoon_tea','food_dessert','dish_beverage','allergen_dairy'],[],[],[]),
  E('草莓奶昔',['cuisine_other','meal_afternoon_tea','food_dessert','dish_beverage','allergen_dairy'],[],[],[]),
  E('巧克力奶昔',['cuisine_other','meal_afternoon_tea','food_dessert','dish_beverage','allergen_dairy'],[],[],[]),
  E('香草奶昔',['cuisine_other','meal_afternoon_tea','food_dessert','dish_beverage','allergen_dairy'],[],[],[]),

  // 俄式
  E('俄式罗宋汤',['cuisine_russian','meal_lunch','meal_dinner','food_soup','dish_soup','allergen_dairy'],[],[],[]),

  // 西班牙
  E('西班牙火腿',['cuisine_spanish','meal_lunch','meal_dinner','food_pork','dish_appetizer'],[],[],[]),

  // 凉瓜牛肉
  E('凉瓜牛肉',['cuisine_yue','meal_lunch','meal_dinner','food_beef','dish_main','allergen_soy'],[],[],[]),

  // 酱香饼别名
  E('土家酱香饼',['cuisine_other','meal_breakfast','meal_lunch','food_pancake','dish_staple','allergen_gluten','allergen_chili','allergen_soy'],[],[],[]),
];

// ===== FULL ONLY (地域性/小众) =====
const fullOnly = [
  // 四川
  E('芋儿鸡',['cuisine_chuan','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_chili'],[],[],[]),
  E('肥肠鸡',['cuisine_chuan','meal_lunch','meal_dinner','food_pork','food_poultry','dish_main','allergen_chili'],[],[],[]),
  E('豆花牛肉',['cuisine_chuan','meal_lunch','meal_dinner','food_beef','dish_main','allergen_chili','allergen_soy'],[],[],[]),
  E('荤豆花',['cuisine_chuan','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_chili','allergen_soy'],[],[],[]),
  E('三大炮',['cuisine_chuan','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten'],[],[],[]),
  E('伤心凉粉',['cuisine_chuan','meal_lunch','meal_dinner','food_vegetarian','dish_snack','allergen_chili','allergen_soy'],[],[],[]),
  E('乐山豆腐脑',['cuisine_chuan','meal_breakfast','meal_lunch','food_vegetarian','dish_snack','allergen_soy','allergen_chili'],[],[],[]),
  E('古蔺麻辣鸡',['cuisine_chuan','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_chili','allergen_sesame'],[],[],[]),
  E('简阳羊肉汤',['cuisine_chuan','meal_breakfast','meal_lunch','meal_dinner','food_soup','food_lamb','dish_soup','health_nourishing'],[],[],[]),
  E('富顺豆花',['cuisine_chuan','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_soy','allergen_chili'],[],[],[]),
  E('猪儿粑',['cuisine_chuan','meal_breakfast','meal_afternoon_tea','food_rice','dish_snack','allergen_gluten'],[],[],[]),
  E('黄粑',['cuisine_chuan','meal_breakfast','meal_afternoon_tea','food_rice','dish_dessert'],[],[],[]),
  E('锅巴肉片',['cuisine_chuan','meal_lunch','meal_dinner','food_pork','dish_main','allergen_gluten','allergen_soy'],[],[],[]),
  E('开水白菜',['cuisine_chuan','meal_lunch','meal_dinner','food_vegetarian','food_soup','dish_soup'],[],[],[]),

  // 广东
  E('顺德双皮奶',['cuisine_yue','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy','allergen_egg'],[],[],[]),
  E('潮州卤鹅',['cuisine_yue','meal_lunch','meal_dinner','food_poultry','dish_appetizer','allergen_soy'],[],[],[]),
  E('顺德炸牛奶',['cuisine_yue','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy','allergen_gluten'],[],[],[]),
  E('湛江生蚝',['cuisine_yue','meal_lunch','meal_dinner','meal_midnight','food_seafood','dish_main','allergen_shellfish','allergen_garlic'],[],[],[]),

  // 湖南
  E('长沙糖油粑粑',['cuisine_xiang','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten'],[],[],[]),
  E('常德米粉',['cuisine_xiang','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_soy'],[],[],[]),

  // 山东
  E('淄博烧烤',['cuisine_lu','meal_lunch','meal_dinner','meal_midnight','food_meat','food_bbq','dish_main','allergen_chili'],[],[],[]),
  E('枣庄辣子鸡',['cuisine_lu','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_chili'],[],[],[]),
  E('临沂糁汤',['cuisine_lu','meal_breakfast','food_soup','dish_soup','allergen_gluten','allergen_soy'],[],[],[]),
  E('青岛辣炒蛤蜊',['cuisine_lu','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_shellfish','allergen_chili'],[],[],[]),
  E('济南黄焖鸡',['cuisine_lu','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_soy','allergen_chili'],[],[],[]),

  // 江苏
  E('扬州煮干丝',['cuisine_su','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_soy'],[],[],[]),
  E('苏州奥灶面',['cuisine_su','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten','allergen_soy'],[],[],[]),
  E('无锡小笼',['cuisine_su','meal_breakfast','meal_lunch','food_bun','dish_snack','allergen_gluten'],[],[],[]),
  E('无锡酱排骨',['cuisine_su','meal_lunch','meal_dinner','food_pork','dish_main','allergen_soy'],[],[],[]),
  E('南京烤鸭',['cuisine_su','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_soy'],[],[],[]),
  E('南京盐水鸭',['cuisine_su','meal_lunch','meal_dinner','food_poultry','dish_appetizer'],[],[],[]),

  // 浙江
  E('杭州片儿川',['cuisine_zhe','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten','allergen_soy'],[],[],[]),
  E('杭州猫耳朵',['cuisine_zhe','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten'],[],[],[]),
  E('宁波烤菜',['cuisine_zhe','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_soy'],[],[],[]),
  E('绍兴黄酒',['cuisine_zhe','meal_dinner','food_alcohol','dish_beverage','allergen_sulfite'],[],[],[]),
  E('绍兴臭豆腐',['cuisine_zhe','meal_lunch','meal_dinner','meal_midnight','food_vegetarian','dish_snack','allergen_soy','allergen_chili'],[],[],[]),
  E('湖州大馄饨',['cuisine_zhe','meal_breakfast','meal_lunch','meal_dinner','food_dumpling','dish_staple','allergen_gluten'],[],[],[]),
  E('舟山海鲜面',['cuisine_zhe','meal_lunch','meal_dinner','food_noodles','food_seafood','dish_staple','allergen_gluten','allergen_shellfish','allergen_fish'],[],[],[]),
  E('台州麦虾',['cuisine_zhe','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_shellfish'],[],[],[]),
  E('缙云烧饼',['cuisine_zhe','meal_breakfast','meal_lunch','food_pancake','dish_snack','allergen_gluten'],[],[],[]),
  E('金华酥饼',['cuisine_zhe','meal_breakfast','meal_afternoon_tea','food_pancake','dish_snack','allergen_gluten'],[],[],[]),

  // 福建
  E('福州捞化',['cuisine_min','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten','allergen_shellfish'],[],[],[]),
  E('厦门沙茶面',['cuisine_min','meal_breakfast','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_shellfish','allergen_peanut'],[],[],[]),
  E('厦门薄饼',['cuisine_min','meal_breakfast','meal_lunch','food_pancake','dish_snack','allergen_gluten'],[],[],[]),
  E('泉州面线糊',['cuisine_min','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten','allergen_shellfish'],[],[],[]),
  E('泉州牛肉羹',['cuisine_min','meal_lunch','meal_dinner','food_beef','food_soup','dish_soup','allergen_soy'],[],[],[]),
  E('漳州卤面',['cuisine_min','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_shellfish'],[],[],[]),
  E('莆田卤面',['cuisine_min','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_shellfish'],[],[],[]),
  E('宁德福鼎肉片',['cuisine_min','meal_breakfast','meal_lunch','meal_dinner','food_pork','dish_snack','allergen_chili'],[],[],[]),
  E('面线糊',['cuisine_min','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten','allergen_shellfish'],[],[],[]),
  E('福州鱼丸',['cuisine_min','meal_breakfast','meal_lunch','food_seafood','dish_snack','allergen_fish'],[],[],[]),

  // 安徽
  E('安庆江毛水饺',['cuisine_anhui','meal_breakfast','meal_lunch','meal_dinner','food_dumpling','dish_staple','allergen_gluten'],[],[],[]),
  E('马鞍山采石矶茶干',['cuisine_anhui','meal_breakfast','meal_lunch','food_vegetarian','dish_snack','allergen_soy'],[],[],[]),
  E('阜阳格拉条',['cuisine_anhui','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten','allergen_sesame','allergen_chili'],[],[],[]),

  // 湖北
  E('武汉豆皮',['cuisine_e','meal_breakfast','meal_lunch','food_rice','dish_staple','allergen_gluten','allergen_egg'],[],[],[]),
  E('武汉面窝',['cuisine_e','meal_breakfast','food_rice','dish_snack','allergen_gluten'],[],[],[]),
  E('武汉糯米包油条',['cuisine_e','meal_breakfast','food_rice','dish_staple','allergen_gluten'],[],[],[]),
  E('黄石港饼',['cuisine_e','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten'],[],[],[]),
  E('宜昌萝卜饺子',['cuisine_e','meal_breakfast','meal_lunch','food_dumpling','dish_snack','allergen_gluten'],[],[],[]),
  E('襄阳牛肉面',['cuisine_e','meal_breakfast','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_soy'],[],[],[]),
  E('孝感麻糖',['cuisine_e','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_sesame'],[],[],[]),
  E('孝感米酒',['cuisine_e','meal_breakfast','meal_afternoon_tea','food_rice','dish_beverage'],[],[],[]),
  E('荆州鱼糕',['cuisine_e','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_fish','allergen_egg'],[],[],[]),
  E('潜江小龙虾',['cuisine_e','meal_lunch','meal_dinner','meal_midnight','food_seafood','dish_main','allergen_shellfish','allergen_chili'],[],[],[]),
  E('潜江油焖大虾',['cuisine_e','meal_lunch','meal_dinner','meal_midnight','food_seafood','dish_main','allergen_shellfish','allergen_chili','allergen_soy'],[],[],[]),

  // 河南
  E('郑州烩面',['cuisine_yu','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten'],[],[],[]),
  E('郑州胡辣汤',['cuisine_yu','meal_breakfast','food_soup','dish_soup','allergen_chili','allergen_gluten','allergen_soy'],[],[],[]),
  E('开封灌汤包',['cuisine_yu','meal_breakfast','meal_lunch','food_bun','dish_snack','allergen_gluten'],[],[],[]),
  E('洛阳水席',['cuisine_yu','meal_lunch','meal_dinner','food_soup','dish_main','allergen_gluten'],[],[],[]),
  E('洛阳浆面条',['cuisine_yu','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten'],[],[],[]),
  E('安阳扁粉菜',['cuisine_yu','meal_breakfast','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_soy'],[],[],[]),
  E('新乡红焖羊肉',['cuisine_yu','meal_lunch','meal_dinner','food_lamb','dish_main','allergen_soy','allergen_chili'],[],[],[]),
  E('南阳方城烩面',['cuisine_yu','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili'],[],[],[]),
  E('信阳炖菜',['cuisine_yu','meal_lunch','meal_dinner','food_meat','food_stew','dish_main','allergen_soy'],[],[],[]),

  // 山西
  E('太原刀削面',['cuisine_jin','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten'],[],[],[]),
  E('太原头脑',['cuisine_jin','meal_breakfast','food_lamb','food_soup','dish_soup','allergen_gluten'],[],[],[]),
  E('太原打卤面',['cuisine_jin','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_soy','allergen_egg'],[],[],[]),
  E('大同刀削面',['cuisine_jin','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten'],[],[],[]),
  E('晋城炒凉粉',['cuisine_jin','meal_lunch','meal_dinner','food_vegetarian','dish_snack','allergen_chili','allergen_soy'],[],[],[]),
  E('忻州定襄蒸肉',['cuisine_jin','meal_lunch','meal_dinner','food_pork','dish_main','allergen_gluten'],[],[],[]),
  E('晋中平遥牛肉',['cuisine_jin','meal_lunch','meal_dinner','food_beef','dish_appetizer','allergen_soy'],[],[],[]),

  // 东北
  E('齐齐哈尔烤肉',['cuisine_dongbei','meal_lunch','meal_dinner','meal_midnight','food_beef','food_bbq','dish_main','allergen_chili'],[],[],[]),
  E('四平李连贵熏肉大饼',['cuisine_dongbei','meal_lunch','meal_dinner','food_pancake','food_pork','dish_staple','allergen_gluten','allergen_soy'],[],[],[]),
  E('延边辣白菜',['cuisine_dongbei','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_chili','allergen_soy','allergen_shellfish'],[],[],[]),
  E('延边米肠',['cuisine_dongbei','meal_lunch','meal_dinner','food_rice','dish_staple','allergen_soy'],[],[],[]),
  E('延边打糕',['cuisine_dongbei','meal_afternoon_tea','food_rice','dish_dessert','allergen_soy'],[],[],[]),
  E('沈阳老边饺子',['cuisine_dongbei','meal_lunch','meal_dinner','food_dumpling','dish_staple','allergen_gluten'],[],[],[]),
  E('锦州烧烤',['cuisine_dongbei','meal_lunch','meal_dinner','meal_midnight','food_meat','food_bbq','dish_main','allergen_chili'],[],[],[]),
  E('哈尔滨红肠',['cuisine_dongbei','meal_lunch','meal_dinner','food_meat','dish_snack'],[],[],[]),
  E('哈尔滨锅包肉',['cuisine_dongbei','meal_lunch','meal_dinner','food_pork','dish_main','allergen_gluten'],[],[],[]),
  E('延边冷面',['cuisine_dongbei','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_soy','allergen_egg'],[],[],[]),
  E('延边石锅拌饭',['cuisine_dongbei','meal_lunch','meal_dinner','food_rice','dish_staple','allergen_egg','allergen_soy','allergen_chili'],[],[],[]),
  E('沈阳炸鸡架',['cuisine_dongbei','meal_lunch','meal_dinner','meal_midnight','food_poultry','dish_snack','allergen_chili'],[],[],[]),
  E('大连海鲜',['cuisine_dongbei','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_shellfish','allergen_fish'],[],[],[]),
  E('大连焖子',['cuisine_dongbei','meal_lunch','meal_dinner','meal_midnight','food_vegetarian','dish_snack','allergen_soy','allergen_garlic','allergen_sesame'],[],[],[]),
  E('抚顺麻辣拌',['cuisine_dongbei','meal_lunch','meal_dinner','meal_midnight','food_meat','food_vegetarian','dish_snack','allergen_chili','allergen_soy','allergen_peanut','allergen_sesame'],[],[],[]),
  E('丹东黄蚬子',['cuisine_dongbei','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_shellfish','allergen_chili'],[],[],[]),
  E('盘锦河蟹',['cuisine_dongbei','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_shellfish'],[],[],[]),

  // 广西
  E('桂林米粉',['cuisine_gui','meal_breakfast','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_soy','allergen_chili','allergen_peanut'],[],[],[]),
  E('柳州螺蛳粉',['cuisine_gui','meal_breakfast','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_soy','allergen_shellfish'],[],[],[]),
  E('南宁老友粉',['cuisine_gui','meal_breakfast','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_soy','allergen_shellfish'],[],[],[]),
  E('梧州龟苓膏',['cuisine_gui','meal_afternoon_tea','food_dessert','dish_dessert'],[],[],[]),
  E('柳州螺蛳鸭脚煲',['cuisine_gui','meal_lunch','meal_dinner','meal_midnight','food_poultry','food_hotpot','dish_main','allergen_chili','allergen_soy','allergen_shellfish'],[],[],[]),
  E('北海虾饼',['cuisine_gui','meal_breakfast','meal_afternoon_tea','food_seafood','dish_snack','allergen_gluten','allergen_shellfish'],[],[],[]),
  E('钦州猪脚粉',['cuisine_gui','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten','allergen_soy'],[],[],[]),

  // 云南
  E('昆明过桥米线',['cuisine_dian','meal_breakfast','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten'],[],[],[]),
  E('曲靖蒸饵丝',['cuisine_dian','meal_breakfast','meal_lunch','food_rice','dish_staple','allergen_chili','allergen_soy'],[],[],[]),
  E('大理酸辣鱼',['cuisine_dian','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_fish','allergen_chili'],[],[],[]),
  E('丽江腊排骨',['cuisine_dian','meal_lunch','meal_dinner','food_pork','dish_main','allergen_chili'],[],[],[]),

  // 贵州
  E('贵阳肠旺面',['cuisine_qian','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_soy'],[],[],[]),
  E('贵阳花溪牛肉粉',['cuisine_qian','meal_breakfast','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili'],[],[],[]),
  E('贵阳丝娃娃',['cuisine_qian','meal_lunch','meal_dinner','food_vegetarian','dish_appetizer','allergen_chili','allergen_soy'],[],[],[]),
  E('贵阳豆腐圆子',['cuisine_qian','meal_lunch','meal_dinner','food_vegetarian','dish_snack','allergen_soy','allergen_chili'],[],[],[]),
  E('贵阳酸汤鱼',['cuisine_qian','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_fish','allergen_chili'],[],[],[]),
  E('遵义羊肉粉',['cuisine_qian','meal_breakfast','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili'],[],[],[]),
  E('遵义豆花面',['cuisine_qian','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_soy'],[],[],[]),
  E('安顺裹卷',['cuisine_qian','meal_lunch','meal_dinner','food_vegetarian','dish_snack','allergen_chili','allergen_soy'],[],[],[]),

  // 海南
  E('陵水酸粉',['cuisine_qiong','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_shellfish'],[],[],[]),
  E('海口清补凉',['cuisine_qiong','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy'],[],[],[]),
  E('三亚椰子鸡',['cuisine_qiong','meal_lunch','meal_dinner','food_poultry','dish_main'],[],[],[]),

  // 西藏
  E('拉萨甜茶',['cuisine_tibetan','meal_afternoon_tea','food_tea','dish_beverage','allergen_dairy'],[],[],[]),
  E('拉萨酥油茶',['cuisine_tibetan','meal_breakfast','meal_afternoon_tea','food_tea','dish_beverage','allergen_dairy'],[],[],[]),
  E('拉萨藏面',['cuisine_tibetan','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten'],[],[],[]),

  // 宁夏
  E('银川羊肉泡馍',['cuisine_northwest','meal_breakfast','meal_lunch','meal_dinner','food_lamb','food_pancake','dish_staple','allergen_gluten','allergen_chili'],[],[],[]),

  // 青海
  E('西宁手抓羊肉',['cuisine_northwest','meal_lunch','meal_dinner','food_lamb','dish_main'],[],[],[]),
  E('西宁酿皮',['cuisine_northwest','meal_breakfast','meal_lunch','meal_dinner','food_gluten','dish_staple','allergen_gluten','allergen_chili','allergen_sesame'],[],[],[]),

  // 甘肃
  E('兰州酿皮',['cuisine_northwest','meal_breakfast','meal_lunch','meal_dinner','food_gluten','dish_staple','allergen_gluten','allergen_chili','allergen_sesame'],[],[],[]),
  E('兰州灰豆子',['cuisine_northwest','meal_afternoon_tea','food_dessert','dish_dessert','allergen_soy'],[],[],[]),
  E('嘉峪关烤肉',['cuisine_northwest','meal_lunch','meal_dinner','meal_midnight','food_lamb','food_bbq','dish_main','allergen_chili'],[],[],[]),
  E('天水呱呱',['cuisine_northwest','meal_breakfast','meal_lunch','food_vegetarian','dish_snack','allergen_chili','allergen_sesame','allergen_soy'],[],[],[]),
  E('天水凉粉',['cuisine_northwest','meal_lunch','meal_dinner','food_vegetarian','dish_snack','allergen_chili','allergen_sesame','allergen_soy'],[],[],[]),
  E('天水杂烩',['cuisine_northwest','meal_lunch','meal_dinner','food_meat','food_soup','dish_main'],[],[],[]),
  E('张掖搓鱼面',['cuisine_northwest','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_soy'],[],[],[]),
  E('平凉羊肉泡馍',['cuisine_northwest','meal_breakfast','meal_lunch','meal_dinner','food_lamb','food_pancake','dish_staple','allergen_gluten','allergen_chili'],[],[],[]),
  E('酒泉糊锅',['cuisine_northwest','meal_breakfast','meal_lunch','food_soup','dish_soup','allergen_gluten','allergen_chili'],[],[],[]),
  E('定西宽粉',['cuisine_northwest','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_soy'],[],[],[]),

  // 陕西
  E('西安羊肉泡馍',['cuisine_northwest','meal_breakfast','meal_lunch','meal_dinner','food_lamb','food_pancake','dish_staple','allergen_gluten','allergen_chili'],[],[],[]),
  E('西安灌汤包',['cuisine_northwest','meal_breakfast','meal_lunch','meal_dinner','food_bun','dish_snack','allergen_gluten'],[],[],[]),
  E('西安甑糕',['cuisine_northwest','meal_breakfast','meal_afternoon_tea','food_rice','dish_dessert','allergen_gluten'],[],[],[]),
  E('西安粉汤羊血',['cuisine_northwest','meal_breakfast','meal_lunch','food_soup','dish_soup','allergen_chili','allergen_gluten'],[],[],[]),
  E('宝鸡擀面皮',['cuisine_northwest','meal_breakfast','meal_lunch','meal_dinner','food_gluten','dish_staple','allergen_gluten','allergen_chili','allergen_sesame'],[],[],[]),
  E('汉中热米皮',['cuisine_northwest','meal_breakfast','meal_lunch','food_rice','dish_staple','allergen_chili'],[],[],[]),
  E('榆林羊杂碎',['cuisine_northwest','meal_breakfast','meal_lunch','food_lamb','food_soup','dish_soup','allergen_chili'],[],[],[]),
  E('安康蒸面',['cuisine_northwest','meal_breakfast','meal_lunch','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_sesame'],[],[],[]),
  E('杨凌蘸水面',['cuisine_northwest','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili'],[],[],[]),

  // 新疆
  E('乌鲁木齐烤包子',['cuisine_xinjiang','meal_breakfast','meal_lunch','meal_dinner','food_bun','food_lamb','dish_snack','allergen_gluten','allergen_onion'],[],[],[]),
  E('喀什烤包子',['cuisine_xinjiang','meal_breakfast','meal_lunch','meal_dinner','food_bun','food_lamb','dish_snack','allergen_gluten','allergen_onion'],[],[],[]),
  E('塔城风干肉',['cuisine_xinjiang','meal_lunch','meal_dinner','food_beef','dish_appetizer'],[],[],[]),
  E('阿勒泰冷水鱼',['cuisine_xinjiang','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_fish'],[],[],[]),

  // 台湾
  E('台湾卤肉饭',['cuisine_taiwan','meal_lunch','meal_dinner','food_rice','food_pork','dish_staple','allergen_soy'],[],[],[]),
  E('台湾蚵仔煎',['cuisine_taiwan','meal_lunch','meal_dinner','food_seafood','dish_snack','allergen_shellfish','allergen_egg','allergen_gluten'],[],[],[]),
  E('台湾鸡排',['cuisine_taiwan','meal_lunch','meal_dinner','meal_midnight','food_poultry','dish_snack','allergen_gluten'],[],[],[]),
  E('台湾大肠包小肠',['cuisine_taiwan','meal_lunch','meal_dinner','meal_midnight','food_meat','food_rice','dish_snack','allergen_soy','allergen_gluten'],[],[],[]),
  E('台湾棺材板',['cuisine_taiwan','meal_lunch','meal_dinner','food_bun','dish_snack','allergen_gluten','allergen_dairy'],[],[],[]),
  E('台湾刈包',['cuisine_taiwan','meal_breakfast','meal_lunch','food_bun','food_pork','dish_snack','allergen_gluten','allergen_soy','allergen_peanut'],[],[],[]),
  E('台湾三杯鸡',['cuisine_taiwan','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_soy','allergen_sesame'],[],[],[]),

  // 香港
  E('香港丝袜奶茶',['cuisine_hongkong','meal_afternoon_tea','food_tea','dish_beverage','allergen_dairy'],[],[],[]),
  E('香港菠萝油',['cuisine_hongkong','meal_breakfast','meal_afternoon_tea','food_bun','dish_snack','allergen_gluten','allergen_dairy'],[],[],[]),
  E('香港鸡蛋仔',['cuisine_hongkong','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_egg','allergen_dairy'],[],[],[]),
  E('香港云吞面',['cuisine_hongkong','meal_breakfast','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_shellfish'],[],[],[]),
  E('香港西多士',['cuisine_hongkong','meal_breakfast','meal_afternoon_tea','food_bun','dish_snack','allergen_gluten','allergen_egg','allergen_dairy','allergen_peanut'],[],[],[]),
  E('香港蛋挞',['cuisine_hongkong','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_egg','allergen_dairy'],[],[],[]),

  // 澳门
  E('澳门猪扒包',['cuisine_macau','meal_lunch','meal_afternoon_tea','food_bun','food_pork','dish_snack','allergen_gluten'],[],[],[]),
  E('澳门葡挞',['cuisine_macau','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_egg','allergen_dairy'],[],[],[]),
  E('澳门水蟹粥',['cuisine_macau','meal_breakfast','meal_lunch','food_congee','food_seafood','dish_staple','allergen_shellfish'],[],[],[]),
  E('澳门葡国鸡',['cuisine_macau','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_dairy','allergen_chili'],[],[],[]),

  // 蒙古
  E('蒙古奶茶',['cuisine_mongolian','meal_breakfast','meal_afternoon_tea','food_tea','dish_beverage','allergen_dairy'],[],[],[]),
  E('蒙古手把肉',['cuisine_mongolian','meal_lunch','meal_dinner','food_lamb','dish_main'],[],[],[]),
  E('蒙古烤羊腿',['cuisine_mongolian','meal_lunch','meal_dinner','food_lamb','food_bbq','dish_main','allergen_chili'],[],[],[]),
  E('蒙古烤全羊',['cuisine_mongolian','meal_lunch','meal_dinner','food_lamb','food_bbq','dish_main','allergen_chili'],[],[],[]),
  E('蒙古馅饼',['cuisine_mongolian','meal_lunch','meal_dinner','food_pancake','food_meat','dish_main','allergen_gluten'],[],[],[]),

  // 新疆
  E('新疆大盘鸡',['cuisine_xinjiang','meal_lunch','meal_dinner','food_poultry','food_noodles','dish_main','allergen_chili','allergen_gluten','allergen_soy'],[],[],[]),
  E('新疆手抓饭',['cuisine_xinjiang','meal_lunch','meal_dinner','food_rice','food_lamb','dish_staple'],[],[],[]),
  E('新疆拌面',['cuisine_xinjiang','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_soy','allergen_chili'],[],[],[]),
  E('新疆炒米粉',['cuisine_xinjiang','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_soy'],[],[],[]),
  E('新疆椒麻鸡',['cuisine_xinjiang','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_chili','allergen_soy'],[],[],[]),

  // 石家庄/河北
  E('驴肉火烧',['cuisine_ji','meal_breakfast','meal_lunch','meal_dinner','food_pancake','food_meat','dish_snack','allergen_gluten'],[],[],[]),
  E('安徽板面',['cuisine_anhui','meal_breakfast','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_soy'],[],[],[]),
  E('淮南牛肉汤',['cuisine_anhui','meal_breakfast','meal_lunch','meal_dinner','food_soup','food_beef','dish_soup','allergen_chili','allergen_soy'],[],[],[]),

  // 江西
  E('南昌拌粉',['cuisine_gan','meal_breakfast','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_soy','allergen_peanut'],[],[],[]),
  E('南昌瓦罐汤',['cuisine_gan','meal_breakfast','meal_lunch','meal_dinner','food_soup','dish_soup','health_nourishing'],[],[],[]),
  E('萍乡莲花血鸭',['cuisine_gan','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_chili','allergen_soy'],[],[],[]),
  E('赣州宁都肉丸',['cuisine_gan','meal_lunch','meal_dinner','food_pork','dish_snack'],[],[],[]),

  // 更多国际
  E('泰式烤鱼',['cuisine_thai','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_fish','allergen_chili'],[],[],[]),
  E('泰式烤鸡',['cuisine_thai','meal_lunch','meal_dinner','food_poultry','dish_main','allergen_chili','allergen_soy'],[],[],[]),
  E('泰式咖喱蟹',['cuisine_thai','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_shellfish','allergen_chili','allergen_dairy'],[],[],[]),
  E('泰式炒空心菜',['cuisine_thai','meal_lunch','meal_dinner','food_vegetarian','dish_main','allergen_chili','allergen_soy','allergen_shellfish'],[],[],[]),
  E('越南牛肉粉',['cuisine_vietnamese','meal_breakfast','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten'],[],[],[]),
  E('越南鸡肉粉',['cuisine_vietnamese','meal_breakfast','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten'],[],[],[]),
  E('越南滴漏咖啡',['cuisine_vietnamese','meal_afternoon_tea','food_coffee','dish_beverage'],[],[],[]),
  E('越南法棍面包',['cuisine_vietnamese','meal_breakfast','meal_lunch','food_bun','dish_staple','allergen_gluten'],[],[],[]),
  E('新加坡咖椰吐司',['cuisine_other','meal_breakfast','meal_afternoon_tea','food_bun','dish_snack','allergen_gluten','allergen_egg','allergen_dairy'],[],[],[]),
  E('新加坡珍多冰',['cuisine_other','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy'],[],[],[]),
  E('新加坡拉茶',['cuisine_other','meal_afternoon_tea','food_tea','dish_beverage','allergen_dairy'],[],[],[]),
  E('马来西亚炒粿条',['cuisine_malaysian','meal_lunch','meal_dinner','food_noodles','dish_staple','allergen_gluten','allergen_chili','allergen_shellfish','allergen_soy'],[],[],[]),
  E('马来西亚肉骨茶',['cuisine_malaysian','meal_breakfast','meal_lunch','meal_dinner','food_pork','food_soup','dish_soup','health_nourishing','allergen_soy'],[],[],[]),
  E('马来西亚沙爹',['cuisine_malaysian','meal_lunch','meal_dinner','meal_midnight','food_meat','food_bbq','dish_snack','allergen_peanut','allergen_chili'],[],[],[]),
  E('马来西亚煎蕊',['cuisine_malaysian','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy'],[],[],[]),
  E('印尼沙爹',['cuisine_other','meal_lunch','meal_dinner','meal_midnight','food_meat','food_bbq','dish_snack','allergen_peanut','allergen_chili'],[],[],[]),
  E('印度酸奶',['cuisine_indian','meal_afternoon_tea','food_dessert','dish_beverage','allergen_dairy'],[],[],[]),
  E('希腊烤肉串',['cuisine_greek','meal_lunch','meal_dinner','food_meat','food_bbq','dish_main'],[],[],[]),
  E('希腊烤鱼',['cuisine_greek','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_fish'],[],[],[]),
  E('法式洋葱汤',['cuisine_french','meal_lunch','meal_dinner','food_soup','dish_soup','allergen_gluten','allergen_dairy'],[],[],[]),
  E('法式焗蜗牛',['cuisine_french','meal_lunch','meal_dinner','food_seafood','dish_appetizer','allergen_dairy','allergen_garlic'],[],[],[]),
  E('法式鹅肝',['cuisine_french','meal_lunch','meal_dinner','food_poultry','dish_appetizer'],[],[],[]),
  E('法式鹅肝酱',['cuisine_french','meal_lunch','meal_dinner','food_poultry','dish_appetizer'],[],[],[]),
  E('法式烤鸡',['cuisine_french','meal_lunch','meal_dinner','food_poultry','dish_main'],[],[],[]),
  E('法式炖牛肉',['cuisine_french','meal_lunch','meal_dinner','food_beef','food_stew','dish_main'],[],[],[]),
  E('法式可丽饼',['cuisine_french','meal_breakfast','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_dairy','allergen_egg'],[],[],[]),
  E('法式舒芙蕾',['cuisine_french','meal_afternoon_tea','food_dessert','dish_dessert','allergen_egg','allergen_dairy','allergen_gluten'],[],[],[]),
  E('西班牙土豆蛋饼',['cuisine_spanish','meal_breakfast','meal_lunch','food_egg','dish_main','allergen_egg'],[],[],[]),
  E('德国猪肘',['cuisine_german','meal_lunch','meal_dinner','food_pork','dish_main'],[],[],[]),
  E('德国面包',['cuisine_german','meal_breakfast','meal_lunch','food_bun','dish_staple','allergen_gluten'],[],[],[]),
  E('德国黑麦面包',['cuisine_german','meal_breakfast','meal_lunch','food_bun','dish_staple','allergen_gluten'],[],[],[]),
  E('德国苹果卷',['cuisine_german','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_egg'],[],[],[]),
  E('英式牧羊人派',['cuisine_british','meal_lunch','meal_dinner','food_lamb','dish_main','allergen_gluten','allergen_dairy'],[],[],[]),
  E('英式烤牛肉',['cuisine_british','meal_lunch','meal_dinner','food_beef','dish_main'],[],[],[]),
  E('美式烤肋排',['cuisine_american','meal_lunch','meal_dinner','food_pork','food_bbq','dish_main'],[],[],[]),
  E('美式烤火鸡',['cuisine_american','meal_lunch','meal_dinner','food_poultry','dish_main'],[],[],[]),
  E('美式肉桂卷',['cuisine_american','meal_breakfast','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten','allergen_dairy','allergen_egg'],[],[],[]),
  E('美式奶昔',['cuisine_american','meal_afternoon_tea','food_dessert','dish_beverage','allergen_dairy'],[],[],[]),
  E('巴西黑豆炖肉',['cuisine_brazilian','meal_lunch','meal_dinner','food_pork','dish_main','allergen_soy'],[],[],[]),
  E('巴西椰子布丁',['cuisine_brazilian','meal_afternoon_tea','food_dessert','dish_dessert','allergen_dairy','allergen_egg'],[],[],[]),
  E('阿根廷烤肉',['cuisine_brazilian','meal_lunch','meal_dinner','food_beef','food_bbq','dish_main','health_high_protein'],[],[],[]),
  E('古巴三明治',['cuisine_other','meal_lunch','meal_dinner','food_bun','food_meat','dish_main','allergen_gluten','allergen_dairy'],[],[],[]),
  E('古巴咖啡',['cuisine_other','meal_afternoon_tea','food_coffee','dish_beverage'],[],[],[]),
  E('摩洛哥塔吉锅',['cuisine_african','meal_lunch','meal_dinner','food_meat','food_stew','dish_main','allergen_chili'],[],[],[]),
  E('埃塞俄比亚英吉拉',['cuisine_african','meal_lunch','meal_dinner','food_gluten','dish_staple','allergen_gluten'],[],[],[]),
  E('抹茶冰沙',['cuisine_other','meal_afternoon_tea','food_dessert','dish_beverage','allergen_dairy'],[],[],[]),
  E('巧克力冰沙',['cuisine_other','meal_afternoon_tea','food_dessert','dish_beverage','allergen_dairy'],[],[],[]),
  E('红糖发糕',['cuisine_other','meal_breakfast','meal_afternoon_tea','food_dessert','dish_dessert','allergen_gluten'],[],[],[]),
  E('番薯糖水',['cuisine_yue','meal_afternoon_tea','food_dessert','dish_dessert'],[],[],[]),
  E('炸串',['cuisine_other','meal_lunch','meal_dinner','meal_midnight','food_meat','dish_snack','allergen_gluten','allergen_chili'],[],[],[]),
  E('山东煎饼',['cuisine_lu','meal_breakfast','meal_lunch','food_pancake','dish_staple','allergen_gluten'],[],[],[]),
  E('天津煎饼果子',['cuisine_tianjin','meal_breakfast','food_pancake','dish_staple','allergen_gluten','allergen_egg'],[],[],[]),
  E('越南甘蔗虾',['cuisine_vietnamese','meal_lunch','meal_dinner','food_seafood','dish_main','allergen_shellfish','allergen_gluten'],[],[],[]),
  E('法式蜗牛',['cuisine_french','meal_lunch','meal_dinner','food_seafood','dish_appetizer','allergen_dairy','allergen_garlic'],[],[],[]),
  E('越南烤肉米粉',['cuisine_vietnamese','meal_lunch','meal_dinner','food_noodles','food_meat','dish_staple','allergen_gluten','allergen_chili','allergen_shellfish'],[],[],[]),
];

// Execute
const commonDB = JSON.parse(fs.readFileSync('./js/ingredients_common.json', 'utf8'));
const fullDB = JSON.parse(fs.readFileSync('./js/ingredients_full.json', 'utf8'));
const ec = new Set(commonDB.items.map(x => x.name));
const ef = new Set(fullDB.items.map(x => x.name));

let ca = 0, fa = 0;
for (const e of common) {
  if (ec.has(e.name)) { console.log('SKIP c: ' + e.name); continue; }
  commonDB.items.push(e); ec.add(e.name); ca++;
}
for (const e of [...common, ...fullOnly]) {
  if (ef.has(e.name)) { console.log('SKIP f: ' + e.name); continue; }
  fullDB.items.push(e); ef.add(e.name); fa++;
}

fs.writeFileSync('./js/ingredients_common.json', JSON.stringify(commonDB, null, 4), 'utf8');
fs.writeFileSync('./js/ingredients_full.json', JSON.stringify(fullDB, null, 4), 'utf8');
console.log('Common: +' + ca + ' total:' + commonDB.items.length);
console.log('Full: +' + fa + ' total:' + fullDB.items.length);